import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ru" | "uz";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Add Patient",
    "nav.logout": "Logout",
    "nav.dashboard": "Dashboard",
    "nav.patients": "Patients",
    "nav.medications": "Medications",
    "nav.alerts": "Alerts",
    "nav.reports": "Reports",
    "nav.analytics": "Analytics",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Transplant patient overview",
    "dashboard.totalPatients": "Total Patients",
    "dashboard.highRisk": "High Risk",
    "dashboard.mediumRisk": "Medium Risk",
    "dashboard.activeAlerts": "Active Alerts",
    "dashboard.riskDistribution": "Risk Distribution",
    "dashboard.noPatients": "No patients yet",
    "dashboard.highRiskPatients": "High-Risk Patients",
    "dashboard.noHighRisk": "No high-risk patients",
    "dashboard.patient": "Patient",
    "dashboard.organ": "Organ",
    "dashboard.daysPostTx": "Days Post-Tx",
    "dashboard.keyLab": "Key Lab",
    "dashboard.risk": "Risk",
    "login.title": "TransplantCare",
    "login.subtitle": "Transplant patient management system",
    "login.signIn": "Sign in",
    "login.signUp": "Create account",
    "login.signInDesc": "Enter your credentials to continue",
    "login.signUpDesc": "Enter your details to create an account",
    "login.fullName": "Full Name",
    "login.email": "Email",
    "login.password": "Password",
    "login.createAccount": "Create Account",
    "login.alreadyHave": "Already have an account?",
    "login.dontHave": "Don't have an account?",
    "login.accountCreated": "Account created",
    "login.checkEmail": "Please check your email to verify your account.",
    "login.forgotPassword": "Forgot password?",
    "login.resetPassword": "Reset Password",
    "login.resetDesc": "Enter your email to receive a password reset link",
    "login.sendResetLink": "Send Reset Link",
    "login.resetSent": "Reset link sent",
    "login.resetSentDesc": "Check your email for a password reset link.",
    "login.backToLogin": "Back to login",
    "login.newPassword": "New Password",
    "login.confirmPassword": "Confirm Password",
    "login.updatePassword": "Update Password",
    "login.passwordUpdated": "Password updated",
    "login.passwordUpdatedDesc": "You can now sign in with your new password.",
    "login.passwordMismatch": "Passwords do not match",
    "role.welcome": "Welcome to TransplantCare",
    "role.selectRole": "Select your role to continue",
    "role.doctor": "Doctor / Healthcare Provider",
    "role.doctorDesc": "Manage patients, review risks, and oversee transplant care",
    "role.patient": "Patient Portal",
    "role.patientDesc": "View your health status, lab results, and care timeline",
    "role.support": "Support",
    "role.supportDesc": "Help users with issues and manage support requests",
    "role.admin": "Administrator",
    "role.adminDesc": "Full system management, users and settings",
    "add.selectOrgan": "Add Patient — Select Organ",
    "add.chooseType": "Choose the transplant type",
    "add.liverTransplant": "Liver Transplant",
    "add.kidneyTransplant": "Kidney Transplant",
    "add.liverDesc": "ALT, AST, Tacrolimus, Bilirubin tracking",
    "add.kidneyDesc": "Creatinine, eGFR, Dialysis history tracking",
    "add.patientInfo": "Patient Information",
    "add.fullName": "Full Name",
    "add.dob": "Date of Birth",
    "add.gender": "Gender",
    "add.male": "Male",
    "add.female": "Female",
    "add.other": "Other",
    "add.transplantDetails": "Transplant Details",
    "add.transplantNumber": "Transplant Number",
    "add.transplantDate": "Transplant Date",
    "add.rejectionType": "Rejection Type",
    "add.dialysisHistory": "Dialysis History",
    "add.yes": "Yes",
    "add.no": "No",
    "add.returnDialysisDate": "Return to Dialysis Date",
    "add.biopsyResult": "Biopsy Result (optional)",
    "add.bloodInfo": "Blood Type Information",
    "add.bloodType": "Patient Blood Type",
    "add.donorBloodType": "Donor Blood Type",
    "add.titerTherapy": "Titer Reduction Therapy Done",
    "add.bloodMismatchWarning": "Blood type mismatch detected! This increases the risk of antibody-mediated rejection (AMR).",
    "add.labResults": "Laboratory Results",
    "add.tacrolimus": "Tacrolimus Level",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Total Bilirubin",
    "add.directBilirubin": "Direct Bilirubin",
    "add.creatinine": "Creatinine",
    "add.egfr": "eGFR",
    "add.proteinuria": "Proteinuria",
    "add.potassium": "Potassium",
    "add.save": "Save Patient",
    "add.patientAdded": "Patient added",
    "add.addLiver": "Add Liver Patient",
    "add.addKidney": "Add Kidney Patient",
    "detail.patientInfo": "Patient Information",
    "detail.underReview": "Under medical review",
    "detail.latestLabs": "Latest Lab Results",
    "detail.aiAdvisory": "AI Advisory & Review",
    "detail.approve": "Approve",
    "detail.orOverride": "or override:",
    "detail.newRiskLevel": "New risk level",
    "detail.overrideReason": "Mandatory reason for override...",
    "detail.overrideRisk": "Override Risk",
    "detail.timeline": "Timeline",
    "detail.noEvents": "No events",
    "detail.added": "Added",
    "detail.dob": "Date of Birth",
    "detail.riskApproved": "Risk approved",
    "detail.provideReason": "Please provide a risk level and reason",
    "detail.riskOverridden": "Risk overridden",
    "detail.addLab": "Add Lab",
    "detail.addNewLab": "Add New Lab Results",
    "detail.saveLab": "Save Lab Results",
    "detail.labAdded": "Lab results added",
    "detail.labAddedEvent": "New lab results recorded",
    "detail.date": "Date",
    "detail.labHistory": "Lab Results History",
    "detail.editDate": "Edit Date",
    "detail.deleteLab": "Delete",
    "detail.confirmDeleteLab": "Delete this lab result?",
    "detail.confirmDeleteLabDesc": "This action cannot be undone. Related risk data will also be removed.",
    "detail.labDeleted": "Lab result deleted",
    "detail.labDateUpdated": "Lab date updated",
    "home.healthStatus": "Your Health Status",
    "home.name": "Name",
    "home.organ": "Organ",
    "home.riskLevel": "Risk Level",
    "home.highRiskWarning": "⚠️ Under medical review. Your care team is monitoring your status.",
    "home.careTimeline": "Care Timeline",
    "home.noEvents": "No events yet",
    "home.latestLabs": "Latest Lab Results",
    "home.recorded": "Recorded",
    "home.noLinked": "No patient record linked to your account yet. Please contact your healthcare provider.",
    "home.loading": "Loading...",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.optional": "Optional",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.date": "Date",
    "common.phone": "Phone",
    "common.tests": "tests",
    // Lab Upload
    "upload.title": "Upload Lab Report",
    "upload.uploadTitle": "Upload Laboratory Report",
    "upload.processing": "Processing report...",
    "upload.confirm": "Confirm Results",
    "upload.description": "Upload a photo or file of your lab report. If one file has results from multiple dates, each will be saved separately.",
    "upload.takePhoto": "Take Photo",
    "upload.uploadFile": "Upload File",
    "upload.aiProcessing": "Extracting lab values with AI...",
    "upload.detectingDates": "Detecting dates, layout and test names",
    "upload.datesDetected": "separate dates detected — each will be saved as a separate lab result",
    "upload.dateLabel": "Date:",
    "upload.enterDateManually": "Enter date manually",
    "upload.dateNotDetected": "Date not detected",
    "upload.dateNotDetectedDesc": "Date not detected — enter manually:",
    "upload.valuesFound": "values found",
    "upload.needsVerification": "needs verification",
    "upload.lowConfidence": "Low confidence — verify:",
    "upload.saveResults": "Save results",
    "upload.confirmResults": "Confirm results",
    "upload.reupload": "Re-upload",
    "upload.resultsSaved": "Results saved for dates",
    "upload.verifyValues": "values need verification",
    "upload.lowConfidenceDesc": "Low confidence values are highlighted.",
    "upload.original": "Original",
    // Lab Results Table
    "lab.noResults": "No lab results available",
    "lab.testName": "Test Name",
    "lab.value": "Value",
    "lab.unit": "Unit",
    "lab.reference": "Reference",
    "lab.status": "Status",
    "lab.normal": "Normal",
    "lab.high": "High",
    "lab.borderline": "Borderline",
    "lab.noTrendData": "No trend data available",
    "lab.latestLabs": "Latest Labs",
    "lab.labHistory": "Lab History",
    "lab.latest": "Latest",
    // Risk Score
    "risk.score": "Risk Score",
    "risk.calculating": "Calculating...",
    "risk.noLabData": "No lab results entered",
    "risk.factors": "Risk factors:",
    "risk.highDetected": "High risk detected",
    "risk.mediumDetected": "Medium risk detected",
    "risk.explanation": "Why this risk level",
    "risk.sinceLastTest": "since last test",
    "risk.lastEvaluation": "Last evaluation",
    // Time
    "time.minAgo": "min ago",
    "time.hourAgo": "h ago",
    "time.dayAgo": "d ago",
    // Priority reasons
    "priority.highRisk": "High risk level (>80)",
    "priority.mediumRisk": "Medium risk level",
    "priority.highLevel": "High risk level",
    "priority.newLab": "New lab uploaded (within 24h)",
    "priority.notReviewed": "days not reviewed",
    "priority.neverReviewed": "Never reviewed",
    "priority.creatinineHigh": "Creatinine high",
    "priority.egfrLow": "eGFR low",
    "priority.potassiumAbnormal": "Potassium abnormal",
    "priority.altHigh": "ALT high",
    "priority.astHigh": "AST high",
    "priority.tacrolimusAbnormal": "Tacrolimus abnormal",
    "priority.bilirubinHigh": "Bilirubin high",
    "priority.cat_critical": "Critical attention",
    "priority.cat_review": "Needs review",
    "priority.cat_stable": "Stable",
    // Dashboard extras
    "dashboard.allPatients": "All Patients",
    // Schedule extras
    "schedule.onSchedule": "On schedule",
    // Prediction extras
    "prediction.disclaimer": "This prediction is AI-assisted and should be reviewed by a healthcare professional.",
    // Patient Alerts
    "patientAlerts.title": "Alerts",
    "patientAlerts.markAllRead": "Mark all read",
    // Edit Patient
    "edit.title": "Edit Patient Information",
    "edit.patientUpdated": "Patient information saved",
    "edit.enterName": "Enter name",
    "edit.none": "None",
    "edit.acute": "Acute",
    "edit.chronic": "Chronic",
    // Patient Profile
    "profile.overview": "Overview",
    "profile.labResults": "Lab Results",
    "profile.trends": "Trends",
    "profile.risk": "Risk",
    "profile.timeline": "Timeline",
    "profile.patientInfo": "Patient Information",
    "profile.fullName": "Full Name",
    "profile.organType": "Organ Type",
    "profile.gender": "Gender",
    "profile.dob": "Date of Birth",
    "profile.transplantDate": "Transplant Date",
    "profile.transplant": "Transplant",
    "profile.highRiskWarning": "⚠️ Your risk level is elevated. Please consult your doctor as soon as possible.",
    "profile.careTimeline": "Care Timeline",
    "profile.noEvents": "No events recorded",
    // Detail
    "detail.patientNotFound": "Patient not found",
    "detail.confirmDelete": "Delete Patient",
    "detail.confirmDeleteDesc": "Are you sure you want to delete this patient? This action cannot be undone.",
    "detail.patientDeleted": "Patient deleted",
    "detail.patientUpdated": "Patient information saved",
    // Analytics
    "analytics.title": "Analytics & Statistics",
    "analytics.subtitle": "National transplant statistics and center comparison",
    "analytics.print": "Print",
    "analytics.exportCSV": "Export CSV",
    "analytics.filters": "Filters",
    "analytics.allYears": "All Years",
    "analytics.allRegions": "All Regions",
    "analytics.allOrgans": "All Organs",
    "analytics.reset": "Reset",
    "analytics.transplantsByYear": "Transplants by Year",
    "analytics.survivalTrends": "National Survival Trends",
    "analytics.centerComparison": "Transplant Center Comparison",
    "analytics.centerName": "Center Name",
    "analytics.region": "Region",
    "analytics.total": "Total",
    "analytics.kidney": "Kidney",
    "analytics.liver": "Liver",
    "analytics.oneYearSurvival": "1Y Survival",
    "analytics.threeYearSurvival": "3Y Survival",
    "analytics.tashkent": "Tashkent",
    "analytics.samarkand": "Samarkand",
    "analytics.vakhidovCenter": "Vakhidov Republican Center",
    "analytics.nephrologyCenter": "Nephrology Center",
    "analytics.nationalMedicalCenter": "National Medical Center",
    "analytics.childrenNationalCenter": "Children's National Center",
    // Reports
    "reports.title": "Reports & Budget",
    "reports.medications": "Medications",
    "reports.equipment": "Equipment",
    "reports.personnel": "Personnel",
    "reports.facilities": "Facilities",
    "reports.totalBudget": "Total Budget",
    "reports.spentYTD": "Spent YTD",
    "reports.remaining": "Remaining",
    "reports.patientsCovered": "Patients Covered",
    "reports.annualAllocation": "Annual allocation",
    "reports.patientTrends": "Patient & Transplant Trends",
    "reports.patients": "Patients",
    "reports.transplants": "Transplants",
    "reports.budgetAllocation": "Budget Allocation",
    "reports.departmentUtilization": "Department Utilization",
    "reports.availableReports": "Available Reports",
    "reports.generateNew": "Generate New",
    "reports.downloaded": "Report downloaded",
    "reports.generated": "Report generated",
    "reports.monthlyPatientRegistry": "Monthly Patient Registry",
    "reports.quarterlyTransplantStats": "Quarterly Transplant Stats",
    "reports.medicationUsageReport": "Medication Usage Report",
    "reports.regionalDistribution": "Regional Distribution Analysis",
    // Alerts
    "alerts.alertCenter": "Alert Center",
    "alerts.filter": "Filter",
    "alerts.all": "All",
    "alerts.critical": "Critical",
    "alerts.warning": "Warning",
    "alerts.warnings": "Warnings",
    "alerts.info": "Info",
    "alerts.unread": "Unread",
    "alerts.resolved": "Resolved",
    "alerts.view": "View",
    "alerts.noAlerts": "No alerts",
    "alerts.markRead": "Mark read",
    "alerts.criticalLabResult": "Critical Lab Result",
    "alerts.medicationStockCritical": "Medication Stock Critical",
    "alerts.missedCheckin": "Missed Medication Check-in",
    "alerts.lowStock": "Low Stock Warning",
    "alerts.scheduledAppointment": "Scheduled Appointment",
    "alerts.labNormal": "Lab Results Normal",
    // Medications
    "medications.inventory": "Medication Inventory",
    "medications.search": "Search medications...",
    "medications.totalMedications": "Total Medications",
    "medications.lowStock": "Low Stock",
    "medications.criticalStock": "Critical Stock",
    "medications.ordersPending": "Orders Pending",
    "medications.medication": "Medication",
    "medications.category": "Category",
    "medications.currentStock": "Current Stock",
    "medications.stockLevel": "Stock Level",
    "medications.monthlyUsage": "Monthly Usage",
    "medications.trend": "Trend",
    "medications.status": "Status",
    "medications.critical": "Critical",
    "medications.low": "Low",
    "medications.inStock": "In Stock",
    "medications.activeLabel": "Active",
    "medications.inactiveLabel": "Inactive",
    "medications.dosages": "Dosages",
    "medications.frequency": "Frequency",
    "medications.noResults": "No results found",
    "analytics.unknown": "Unknown",
    // Patients
    "patients.total": "Total Recipients",
    "patients.alive": "Alive",
    "patients.onDialysis": "On Dialysis",
    "patients.deceased": "Deceased",
    "patients.recipientsList": "Recipients List",
    "patients.export": "Export",
    "patients.newTransplant": "New Transplant",
    "patients.search": "Search patients...",
    "patients.organ": "Organ",
    "patients.allOrgans": "All Organs",
    "patients.allStatus": "All Status",
    "patients.name": "Name",
    "patients.ageGender": "Age/Gender",
    "patients.transplantDate": "Transplant Date",
    "patients.region": "Region",
    "patients.status": "Status",
    "patients.riskScore": "Risk Score",
    // Medications (patient)
    "med.title": "Medications",
    "med.subtitle": "Patient medication tracking and dosage management",
    "med.addMedication": "Add Medication",
    "med.medicationName": "Medication Name",
    "med.dosage": "Dosage",
    "med.frequency": "Frequency",
    "med.startDate": "Start Date",
    "med.endDate": "End Date",
    "med.notes": "Notes",
    "med.actions": "Actions",
    "med.activeMeds": "Active Medications",
    "med.stoppedMeds": "Stopped",
    "med.totalChanges": "Dosage Changes",
    "med.changeHistory": "Change History",
    "med.noMedications": "No medications added yet",
    "med.noStoppedMeds": "No stopped medications",
    "med.noChanges": "No dosage changes",
    "med.changeDosage": "Change Dosage",
    "med.changeDosageTitle": "Change Dosage",
    "med.currentDosage": "Current Dosage",
    "med.newDosage": "New Dosage",
    "med.reason": "Reason",
    "med.reasonPlaceholder": "Reason for dosage change...",
    "med.dosageChanged": "Dosage changed successfully",
    "med.fillRequired": "Please fill in required fields",
    "med.added": "Medication added",
    "med.stop": "Stop",
    "med.stopConfirm": "Stop Medication?",
    "med.stopDesc": "Are you sure you want to stop this medication?",
    "med.search": "Search medications...",
    "med.daily": "Once daily",
    "med.twice_daily": "Twice daily",
    "med.threeTimesDaily": "Three times daily",
    "med.three_times": "Three times daily",
    "med.weekly": "Weekly",
    "med.as_needed": "As needed",
    "med.unknownMed": "Unknown medication",
    "med.myMedications": "My Medications",
    "med.selectMedication": "Select medication",
    "med.customMedication": "Other (custom)",
    "med.selectDosage": "Select dosage",
    "med.customDosage": "Custom dosage",
    "med.group": "Group",
    "medGroup.cni": "Calcineurin Inhibitors (CNI)",
    "medGroup.antimetabolite": "Antimetabolites (MMF/MPA)",
    "medGroup.mtor": "mTOR Inhibitors",
    "medGroup.corticosteroid": "Corticosteroids",
    "medGroup.other": "Other",
    "patients.lowRisk": "Low Risk",
    "med.perMonth": "mo",
    "upload.labUploadedEvent": "Lab report uploaded via OCR",
    // Organ & gender display
    "organ.liver": "Liver",
    "organ.kidney": "Kidney",
    "gender.male": "Male",
    "gender.female": "Female",
    "gender.other": "Other",
    // Risk level labels
    "risk.high": "HIGH",
    "risk.medium": "MEDIUM",
    "risk.low": "LOW",
    // Risk flags (for translating DB-stored flags)
    "flag.tacrolimus_low": "Tacrolimus low",
    "flag.tacrolimus_high": "Tacrolimus high",
    "flag.alt_critical": "ALT critical",
    "flag.alt_elevated": "ALT elevated",
    "flag.ast_critical": "AST critical",
    "flag.ast_elevated": "AST elevated",
    "flag.bilirubin_critical": "Bilirubin critical",
    "flag.bilirubin_elevated": "Bilirubin elevated",
    "flag.retransplant": "Re-transplant patient",
    "flag.creatinine_critical": "Creatinine critical",
    "flag.creatinine_elevated": "Creatinine elevated",
    "flag.egfr_very_low": "eGFR very low",
    "flag.egfr_low": "eGFR low",
    "flag.dialysis_history": "Dialysis history",
    // Time
    "time.justNow": "just now",
    "time.minutesAgo": "min ago",
    "time.hoursAgo": "h ago",
    "time.daysAgo": "d ago",
    // Months
    "month.jan": "Jan", "month.feb": "Feb", "month.mar": "Mar",
    "month.apr": "Apr", "month.may": "May", "month.jun": "Jun",
    "month.jul": "Jul", "month.aug": "Aug", "month.sep": "Sep",
    "month.oct": "Oct", "month.nov": "Nov", "month.dec": "Dec",
    // Events
    "event.txAdded": "Transplant added",
    "event.dialysisRecorded": "Return to dialysis recorded",
    "event.riskOverridden": "Risk overridden",
    // Date
    "date.year": "Year",
    "date.month": "Month",
    "date.day": "Day",
    "date.monthSuffix": "mo",
    // Region
    "add.region": "Region",
    "add.district": "District",
    // Misc
    "add.selectPlaceholder": "Select...",
    "error.title": "Error",
    "error.sessionExpired": "Session expired. Please sign in again.",
    "error.invalidCredentials": "Invalid login or password.",
    "error.emailNotConfirmed": "Email not confirmed. Check your inbox.",
    "error.alreadyRegistered": "This email is already registered.",
    "error.duplicateKey": "This data already exists.",
    "error.noPermission": "You do not have permission for this action.",
    "error.noInternet": "No internet connection. Please try again.",
    "error.networkError": "Network error. Check your connection.",
    "error.unexpected": "An unexpected error occurred. Please try again.",
    "error.unknown": "Unknown error occurred.",
    "translate.writtenIn": "Written in",
    "translate.translating": "Translating...",
    "translate.noteLanguage": "Note language",
    "prediction.title": "Predictive Rejection Risk",
    "prediction.analyzing": "Analyzing trends...",
    "prediction.currentRisk": "Current Risk",
    "prediction.prediction": "Prediction",
    "prediction.timeframe": "Timeframe",
    "prediction.reasons": "Prediction Reasons",
    "prediction.noPrediction": "Not enough data for prediction",
    "prediction.patientNotice": "Your doctor may review your recent laboratory results.",
    "dashboard.predictions": "Rejection Predictions",
    "dashboard.noHighRiskDesc": "No high-risk patients currently",
    "dashboard.addFirstPatient": "Add your first patient",
    "dashboard.patientsAttention": "Patients Requiring Attention Today",
    "dashboard.priorityDisclaimer": "Priority scores are AI-assisted and should support, not replace, clinical judgment.",
    "dashboard.priority": "Priority",
    "dashboard.status": "Status",
    "dashboard.reasons": "Reasons",
    "dashboard.criticalCount": "critical",
    "dashboard.reviewCount": "review",
    "dashboard.allStable": "All patients are stable",
    "dashboard.noUrgent": "No patients requiring urgent attention at this time",
    "schedule.title": "Lab Schedule",
    "schedule.overdueTitle": "Patients With Overdue Labs",
    "schedule.lastLabDate": "Last Lab Date",
    "schedule.expectedDate": "Expected Lab Date",
    "schedule.status": "Status",
    "schedule.overdue": "Overdue",
    "schedule.dueSoon": "Due soon",
    "schedule.upcoming": "Upcoming",
    "schedule.completed": "Completed",
    "schedule.scheduledLab": "Scheduled laboratory test",
    "schedule.overdueReminder": "Your scheduled lab test is overdue. Please upload your results.",
    "schedule.dueSoonReminder": "Your next laboratory test is scheduled in 3 days.",
    "schedule.medicalNote": "Regular laboratory monitoring is essential after transplant surgery.",
    "schedule.disclaimer": "Priority scores are AI-assisted and should support, not replace, clinical judgment.",
  },
  ru: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Добавить пациента",
    "nav.logout": "Выход",
    "nav.dashboard": "Панель",
    "nav.patients": "Пациенты",
    "nav.medications": "Препараты",
    "nav.alerts": "Оповещения",
    "nav.reports": "Отчёты",
    "nav.analytics": "Аналитика",
    "dashboard.title": "Панель управления",
    "dashboard.subtitle": "Обзор пациентов с трансплантацией",
    "dashboard.totalPatients": "Всего пациентов",
    "dashboard.highRisk": "Высокий риск",
    "dashboard.mediumRisk": "Средний риск",
    "dashboard.activeAlerts": "Активные оповещения",
    "dashboard.riskDistribution": "Распределение рисков",
    "dashboard.noPatients": "Пациентов пока нет",
    "dashboard.highRiskPatients": "Пациенты высокого риска",
    "dashboard.noHighRisk": "Нет пациентов высокого риска",
    "dashboard.patient": "Пациент",
    "dashboard.organ": "Орган",
    "dashboard.daysPostTx": "Дней после Тх",
    "dashboard.keyLab": "Лаб. данные",
    "dashboard.risk": "Риск",
    "login.title": "TransplantCare",
    "login.subtitle": "Система управления пациентами с трансплантацией",
    "login.signIn": "Войти",
    "login.signUp": "Создать аккаунт",
    "login.signInDesc": "Введите данные для входа",
    "login.signUpDesc": "Введите данные для создания аккаунта",
    "login.fullName": "Полное имя",
    "login.email": "Электронная почта",
    "login.password": "Пароль",
    "login.createAccount": "Создать аккаунт",
    "login.alreadyHave": "Уже есть аккаунт?",
    "login.dontHave": "Нет аккаунта?",
    "login.accountCreated": "Аккаунт создан",
    "login.checkEmail": "Проверьте почту для подтверждения.",
    "login.forgotPassword": "Забыли пароль?",
    "login.resetPassword": "Сброс пароля",
    "login.resetDesc": "Введите email для получения ссылки сброса пароля",
    "login.sendResetLink": "Отправить ссылку",
    "login.resetSent": "Ссылка отправлена",
    "login.resetSentDesc": "Проверьте почту для ссылки сброса пароля.",
    "login.backToLogin": "Назад к входу",
    "login.newPassword": "Новый пароль",
    "login.confirmPassword": "Подтвердите пароль",
    "login.updatePassword": "Обновить пароль",
    "login.passwordUpdated": "Пароль обновлён",
    "login.passwordUpdatedDesc": "Теперь вы можете войти с новым паролем.",
    "login.passwordMismatch": "Пароли не совпадают",
    "role.welcome": "Добро пожаловать в TransplantCare",
    "role.selectRole": "Выберите роль для продолжения",
    "role.doctor": "Врач / Медицинский работник",
    "role.doctorDesc": "Управление пациентами, анализ рисков и контроль трансплантации",
    "role.patient": "Портал пациента",
    "role.patientDesc": "Просмотр состояния здоровья, результатов анализов и хронологии лечения",
    "role.support": "Поддержка",
    "role.supportDesc": "Помощь пользователям и управление запросами поддержки",
    "role.admin": "Администратор",
    "role.adminDesc": "Полное управление системой, пользователями и настройками",
    "add.selectOrgan": "Добавить пациента — Выбор органа",
    "add.chooseType": "Выберите тип трансплантации",
    "add.liverTransplant": "Трансплантация печени",
    "add.kidneyTransplant": "Трансплантация почки",
    "add.liverDesc": "Отслеживание ALT, AST, Такролимус, Билирубин",
    "add.kidneyDesc": "Отслеживание Креатинин, СКФ, История диализа",
    "add.patientInfo": "Информация о пациенте",
    "add.fullName": "Полное имя",
    "add.dob": "Дата рождения",
    "add.gender": "Пол",
    "add.male": "Мужской",
    "add.female": "Женский",
    "add.other": "Другой",
    "add.transplantDetails": "Детали трансплантации",
    "add.transplantNumber": "Номер трансплантации",
    "add.transplantDate": "Дата трансплантации",
    "add.rejectionType": "Тип отторжения",
    "add.dialysisHistory": "История диализа",
    "add.yes": "Да",
    "add.no": "Нет",
    "add.returnDialysisDate": "Дата возвращения на диализ",
    "add.biopsyResult": "Результат биопсии (необязательно)",
    "add.bloodInfo": "Информация о группе крови",
    "add.bloodType": "Группа крови пациента",
    "add.donorBloodType": "Группа крови донора",
    "add.titerTherapy": "Терапия снижения титра проведена",
    "add.bloodMismatchWarning": "Обнаружено несоответствие группы крови! Это повышает риск антителоопосредованного отторжения (AMR).",
    "add.labResults": "Лабораторные результаты",
    "add.tacrolimus": "Уровень такролимуса",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Общий билирубин",
    "add.directBilirubin": "Прямой билирубин",
    "add.creatinine": "Креатинин",
    "add.egfr": "СКФ",
    "add.proteinuria": "Протеинурия",
    "add.potassium": "Калий",
    "add.save": "Сохранить пациента",
    "add.patientAdded": "Пациент добавлен",
    "add.addLiver": "Добавить пациента (Печень)",
    "add.addKidney": "Добавить пациента (Почка)",
    "detail.patientInfo": "Информация о пациенте",
    "detail.underReview": "На медицинском контроле",
    "detail.latestLabs": "Последние результаты анализов",
    "detail.aiAdvisory": "ИИ-консультация и проверка",
    "detail.approve": "Утвердить",
    "detail.orOverride": "или переопределить:",
    "detail.newRiskLevel": "Новый уровень риска",
    "detail.overrideReason": "Обязательная причина переопределения...",
    "detail.overrideRisk": "Переопределить риск",
    "detail.timeline": "Хронология",
    "detail.noEvents": "Нет событий",
    "detail.added": "Добавлен",
    "detail.dob": "Дата рождения",
    "detail.riskApproved": "Риск утверждён",
    "detail.provideReason": "Укажите уровень риска и причину",
    "detail.riskOverridden": "Риск переопределён",
    "detail.addLab": "Добавить анализ",
    "detail.addNewLab": "Добавить новые результаты анализов",
    "detail.saveLab": "Сохранить результаты",
    "detail.labAdded": "Результаты анализов добавлены",
    "detail.labAddedEvent": "Записаны новые результаты анализов",
    "detail.date": "Дата",
    "detail.labHistory": "История анализов",
    "detail.editDate": "Изменить дату",
    "detail.deleteLab": "Удалить",
    "detail.confirmDeleteLab": "Удалить этот результат анализа?",
    "detail.confirmDeleteLabDesc": "Это действие нельзя отменить. Связанные данные о рисках также будут удалены.",
    "detail.labDeleted": "Результат анализа удалён",
    "detail.labDateUpdated": "Дата анализа обновлена",
    "home.healthStatus": "Ваше состояние здоровья",
    "home.name": "Имя",
    "home.organ": "Орган",
    "home.riskLevel": "Уровень риска",
    "home.highRiskWarning": "⚠️ На медицинском контроле. Ваша команда следит за вашим состоянием.",
    "home.careTimeline": "Хронология лечения",
    "home.noEvents": "Пока нет событий",
    "home.latestLabs": "Последние результаты анализов",
    "home.recorded": "Записано",
    "home.noLinked": "Запись пациента ещё не привязана к вашему аккаунту.",
    "home.loading": "Загрузка...",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.optional": "Необязательно",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.date": "Дата",
    "common.phone": "Телефон",
    "common.tests": "тестов",
    "upload.title": "Загрузить отчёт",
    "upload.uploadTitle": "Загрузка лабораторного отчёта",
    "upload.processing": "Обработка отчёта...",
    "upload.confirm": "Подтвердить результаты",
    "upload.description": "Загрузите фото или файл лабораторного отчёта. Если в файле есть результаты за несколько дат, каждая будет сохранена отдельно.",
    "upload.takePhoto": "Сделать фото",
    "upload.uploadFile": "Загрузить файл",
    "upload.aiProcessing": "AI извлекает лабораторные значения...",
    "upload.detectingDates": "Определяются даты, макет и названия тестов",
    "upload.datesDetected": "отдельных дат обнаружено — каждая будет сохранена как отдельный результат",
    "upload.dateLabel": "Дата:",
    "upload.enterDateManually": "Введите дату вручную",
    "upload.dateNotDetected": "Дата не определена",
    "upload.dateNotDetectedDesc": "Дата не определена — введите вручную:",
    "upload.valuesFound": "значений найдено",
    "upload.needsVerification": "требует проверки",
    "upload.lowConfidence": "Низкая уверенность — проверьте:",
    "upload.saveResults": "Сохранить результаты",
    "upload.confirmResults": "Подтвердить результаты",
    "upload.reupload": "Загрузить заново",
    "upload.resultsSaved": "Результаты сохранены для дат",
    "upload.verifyValues": "значений требуют проверки",
    "upload.lowConfidenceDesc": "Значения с низкой уверенностью выделены.",
    "upload.original": "Оригинал",
    "lab.noResults": "Нет результатов анализов",
    "lab.testName": "Название теста",
    "lab.value": "Значение",
    "lab.unit": "Единица",
    "lab.reference": "Норма",
    "lab.status": "Статус",
    "lab.normal": "Норма",
    "lab.high": "Высокий",
    "lab.borderline": "Пограничный",
    "lab.noTrendData": "Нет данных для трендов",
    "lab.latestLabs": "Последние анализы",
    "lab.labHistory": "История анализов",
    "lab.latest": "Последний",
    "risk.score": "Оценка риска",
    "risk.calculating": "Расчёт...",
    "risk.noLabData": "Результаты анализов не введены",
    "risk.factors": "Факторы риска:",
    "risk.highDetected": "Обнаружен высокий риск",
    "risk.mediumDetected": "Обнаружен средний риск",
    "risk.explanation": "Почему такой уровень риска",
    "risk.sinceLastTest": "с последнего теста",
    "risk.lastEvaluation": "Последняя оценка",
    "time.minAgo": "мин назад",
    "time.hourAgo": "ч назад",
    "time.dayAgo": "д назад",
    "priority.highRisk": "Высокий уровень риска (>80)",
    "priority.mediumRisk": "Средний уровень риска",
    "priority.highLevel": "Высокий уровень риска",
    "priority.newLab": "Новый анализ загружен (за 24ч)",
    "priority.notReviewed": "дней без проверки",
    "priority.neverReviewed": "Никогда не проверялся",
    "priority.creatinineHigh": "Креатинин повышен",
    "priority.egfrLow": "eGFR снижен",
    "priority.potassiumAbnormal": "Калий отклонён",
    "priority.altHigh": "ALT повышен",
    "priority.astHigh": "AST повышен",
    "priority.tacrolimusAbnormal": "Такролимус отклонён",
    "priority.bilirubinHigh": "Билирубин повышен",
    "priority.cat_critical": "Срочное внимание",
    "priority.cat_review": "Требует проверки",
    "priority.cat_stable": "Стабильный",
    "dashboard.allPatients": "Все пациенты",
    "schedule.onSchedule": "По графику",
    "prediction.disclaimer": "Этот прогноз создан с помощью ИИ и должен быть проверен медицинским специалистом.",
    "patientAlerts.title": "Оповещения",
    "patientAlerts.markAllRead": "Отметить все прочитанными",
    "edit.title": "Редактировать данные пациента",
    "edit.patientUpdated": "Данные пациента сохранены",
    "edit.enterName": "Введите имя",
    "edit.none": "Нет",
    "edit.acute": "Острый",
    "edit.chronic": "Хронический",
    "profile.overview": "Обзор",
    "profile.labResults": "Анализы",
    "profile.trends": "Тренды",
    "profile.risk": "Риск",
    "profile.timeline": "Хронология",
    "profile.patientInfo": "Информация о пациенте",
    "profile.fullName": "Полное имя",
    "profile.organType": "Тип органа",
    "profile.gender": "Пол",
    "profile.dob": "Дата рождения",
    "profile.transplantDate": "Дата трансплантации",
    "profile.transplant": "Трансплантация",
    "profile.highRiskWarning": "⚠️ Уровень риска повышен. Обратитесь к врачу как можно скорее.",
    "profile.careTimeline": "Хронология лечения",
    "profile.noEvents": "Нет записанных событий",
    "detail.patientNotFound": "Пациент не найден",
    "detail.confirmDelete": "Удалить пациента",
    "detail.confirmDeleteDesc": "Вы уверены, что хотите удалить этого пациента? Это действие нельзя отменить.",
    "detail.patientDeleted": "Пациент удалён",
    "detail.patientUpdated": "Данные пациента сохранены",
    "analytics.title": "Аналитика и статистика",
    "analytics.subtitle": "Национальная статистика трансплантации",
    "analytics.print": "Печать",
    "analytics.exportCSV": "Экспорт CSV",
    "analytics.filters": "Фильтры",
    "analytics.allYears": "Все годы",
    "analytics.allRegions": "Все регионы",
    "analytics.allOrgans": "Все органы",
    "analytics.reset": "Сброс",
    "analytics.transplantsByYear": "Трансплантации по годам",
    "analytics.survivalTrends": "Тренды выживаемости",
    "analytics.centerComparison": "Сравнение центров",
    "analytics.centerName": "Название центра",
    "analytics.region": "Регион",
    "analytics.total": "Всего",
    "analytics.kidney": "Почка",
    "analytics.liver": "Печень",
    "analytics.oneYearSurvival": "1 год выжив.",
    "analytics.threeYearSurvival": "3 года выжив.",
    "analytics.tashkent": "Ташкент",
    "analytics.samarkand": "Самарканд",
    "analytics.vakhidovCenter": "Республиканский центр им. Вахидова",
    "analytics.nephrologyCenter": "Центр нефрологии",
    "analytics.nationalMedicalCenter": "Национальный мед. центр",
    "analytics.childrenNationalCenter": "Детский нац. центр",
    "reports.title": "Отчёты и бюджет",
    "reports.medications": "Медикаменты",
    "reports.equipment": "Оборудование",
    "reports.personnel": "Персонал",
    "reports.facilities": "Помещения",
    "reports.totalBudget": "Общий бюджет",
    "reports.spentYTD": "Потрачено",
    "reports.remaining": "Остаток",
    "reports.patientsCovered": "Пациенты",
    "reports.annualAllocation": "Годовой бюджет",
    "reports.patientTrends": "Тренды пациентов",
    "reports.patients": "Пациенты",
    "reports.transplants": "Трансплантации",
    "reports.budgetAllocation": "Распределение бюджета",
    "reports.departmentUtilization": "Использование по отделам",
    "reports.availableReports": "Доступные отчёты",
    "reports.generateNew": "Новый отчёт",
    "reports.downloaded": "Отчёт скачан",
    "reports.generated": "Отчёт сформирован",
    "reports.monthlyPatientRegistry": "Месячный реестр пациентов",
    "reports.quarterlyTransplantStats": "Квартальная статистика",
    "reports.medicationUsageReport": "Отчёт по медикаментам",
    "reports.regionalDistribution": "Региональный анализ",
    "alerts.alertCenter": "Центр оповещений",
    "alerts.filter": "Фильтр",
    "alerts.all": "Все",
    "alerts.critical": "Критические",
    "alerts.warning": "Предупреждения",
    "alerts.warnings": "Предупреждения",
    "alerts.info": "Информация",
    "alerts.unread": "Непрочитанные",
    "alerts.resolved": "Решённые",
    "alerts.view": "Просмотр",
    "alerts.noAlerts": "Нет оповещений",
    "alerts.markRead": "Прочитано",
    "alerts.criticalLabResult": "Критический анализ",
    "alerts.medicationStockCritical": "Критический запас лекарств",
    "alerts.missedCheckin": "Пропущен приём",
    "alerts.lowStock": "Низкий запас",
    "alerts.scheduledAppointment": "Запланированный приём",
    "alerts.labNormal": "Анализы в норме",
    "medications.inventory": "Склад медикаментов",
    "medications.search": "Поиск...",
    "medications.totalMedications": "Всего препаратов",
    "medications.lowStock": "Низкий запас",
    "medications.criticalStock": "Критический запас",
    "medications.ordersPending": "Ожидают заказа",
    "medications.medication": "Препарат",
    "medications.category": "Категория",
    "medications.currentStock": "Текущий запас",
    "medications.stockLevel": "Уровень запаса",
    "medications.monthlyUsage": "Месячный расход",
    "medications.trend": "Тренд",
    "medications.status": "Статус",
    "medications.critical": "Критический",
    "medications.low": "Низкий",
    "medications.inStock": "В наличии",
    "medications.activeLabel": "Активные",
    "medications.inactiveLabel": "Неактивные",
    "medications.dosages": "Дозировки",
    "medications.frequency": "Частота",
    "medications.noResults": "Результатов не найдено",
    "analytics.unknown": "Неизвестно",
    "patients.total": "Всего реципиентов",
    "patients.alive": "Живы",
    "patients.onDialysis": "На диализе",
    "patients.deceased": "Умершие",
    "patients.recipientsList": "Список реципиентов",
    "patients.export": "Экспорт",
    "patients.newTransplant": "Новая трансплантация",
    "patients.search": "Поиск пациентов...",
    "patients.organ": "Орган",
    "patients.allOrgans": "Все органы",
    "patients.allStatus": "Все статусы",
    "patients.name": "Имя",
    "patients.ageGender": "Возраст/Пол",
    "patients.transplantDate": "Дата трансплантации",
    "patients.region": "Регион",
    "patients.status": "Статус",
    "patients.riskScore": "Риск",
    "med.title": "Медикаменты",
    "med.subtitle": "Отслеживание медикаментов и управление дозировкой",
    "med.addMedication": "Добавить препарат",
    "med.medicationName": "Название препарата",
    "med.dosage": "Дозировка",
    "med.frequency": "Частота приёма",
    "med.startDate": "Дата начала",
    "med.endDate": "Дата окончания",
    "med.notes": "Заметки",
    "med.actions": "Действия",
    "med.activeMeds": "Активные препараты",
    "med.stoppedMeds": "Отменённые",
    "med.totalChanges": "Изменения дозировки",
    "med.changeHistory": "История изменений",
    "med.noMedications": "Препараты ещё не добавлены",
    "med.noStoppedMeds": "Нет отменённых препаратов",
    "med.noChanges": "Нет изменений дозировки",
    "med.changeDosage": "Изменить дозу",
    "med.changeDosageTitle": "Изменение дозировки",
    "med.currentDosage": "Текущая дозировка",
    "med.newDosage": "Новая дозировка",
    "med.reason": "Причина",
    "med.reasonPlaceholder": "Причина изменения дозировки...",
    "med.dosageChanged": "Дозировка успешно изменена",
    "med.fillRequired": "Заполните обязательные поля",
    "med.added": "Препарат добавлен",
    "med.stop": "Отменить",
    "med.stopConfirm": "Отменить препарат?",
    "med.stopDesc": "Вы уверены, что хотите отменить этот препарат?",
    "med.search": "Поиск препаратов...",
    "med.daily": "Раз в день",
    "med.twice_daily": "Два раза в день",
    "med.threeTimesDaily": "Три раза в день",
    "med.three_times": "Три раза в день",
    "med.weekly": "Раз в неделю",
    "med.as_needed": "По необходимости",
    "med.unknownMed": "Неизвестный препарат",
    "med.myMedications": "Мои медикаменты",
    "med.selectMedication": "Выберите препарат",
    "med.customMedication": "Другой (ввести вручную)",
    "med.selectDosage": "Выберите дозировку",
    "med.customDosage": "Своя дозировка",
    "med.group": "Группа",
    "medGroup.cni": "Ингибиторы кальциневрина (CNI)",
    "medGroup.antimetabolite": "Антиметаболиты (MMF/MPA)",
    "medGroup.mtor": "Ингибиторы mTOR",
    "medGroup.corticosteroid": "Кортикостероиды",
    "medGroup.other": "Прочие",
    "patients.lowRisk": "Низкий риск",
    "med.perMonth": "мес",
    "upload.labUploadedEvent": "Лабораторный отчёт загружен через OCR",
    "organ.liver": "Печень",
    "organ.kidney": "Почка",
    "gender.male": "Мужской",
    "gender.female": "Женский",
    "gender.other": "Другой",
    "risk.high": "ВЫСОКИЙ",
    "risk.medium": "СРЕДНИЙ",
    "risk.low": "НИЗКИЙ",
    "flag.tacrolimus_low": "Такролимус низкий",
    "flag.tacrolimus_high": "Такролимус высокий",
    "flag.alt_critical": "ALT критический",
    "flag.alt_elevated": "ALT повышен",
    "flag.ast_critical": "AST критический",
    "flag.ast_elevated": "AST повышен",
    "flag.bilirubin_critical": "Билирубин критический",
    "flag.bilirubin_elevated": "Билирубин повышен",
    "flag.retransplant": "Повторная трансплантация",
    "flag.creatinine_critical": "Креатинин критический",
    "flag.creatinine_elevated": "Креатинин повышен",
    "flag.egfr_very_low": "СКФ очень низкий",
    "flag.egfr_low": "СКФ низкий",
    "flag.dialysis_history": "История диализа",
    "time.justNow": "только что",
    "time.minutesAgo": "мин назад",
    "time.hoursAgo": "ч назад",
    "time.daysAgo": "д назад",
    "month.jan": "Янв", "month.feb": "Фев", "month.mar": "Мар",
    "month.apr": "Апр", "month.may": "Май", "month.jun": "Июн",
    "month.jul": "Июл", "month.aug": "Авг", "month.sep": "Сен",
    "month.oct": "Окт", "month.nov": "Ноя", "month.dec": "Дек",
    "event.txAdded": "Трансплантация добавлена",
    "event.dialysisRecorded": "Возврат на диализ записан",
    "event.riskOverridden": "Риск переопределён",
    "date.year": "Год",
    "date.month": "Месяц",
    "date.day": "День",
    "date.monthSuffix": "мес",
    "add.region": "Регион",
    "add.district": "Район",
    "add.selectPlaceholder": "Выберите...",
    "error.title": "Ошибка",
    "error.sessionExpired": "Сессия истекла. Войдите снова.",
    "error.invalidCredentials": "Неверный логин или пароль.",
    "error.emailNotConfirmed": "Email не подтверждён. Проверьте почту.",
    "error.alreadyRegistered": "Этот email уже зарегистрирован.",
    "error.duplicateKey": "Эти данные уже существуют.",
    "error.noPermission": "У вас нет разрешения на это действие.",
    "error.noInternet": "Нет подключения к интернету. Попробуйте снова.",
    "error.networkError": "Сетевая ошибка. Проверьте подключение.",
    "error.unexpected": "Произошла непредвиденная ошибка.",
    "translate.writtenIn": "Написано на",
    "translate.translating": "Переводим...",
    "translate.noteLanguage": "Язык заметки",
    "error.unknown": "Неизвестная ошибка.",
    "prediction.title": "Прогноз отторжения",
    "prediction.analyzing": "Анализ трендов...",
    "prediction.currentRisk": "Текущий риск",
    "prediction.prediction": "Прогноз",
    "prediction.timeframe": "Период",
    "prediction.reasons": "Причины прогноза",
    "prediction.noPrediction": "Недостаточно данных для прогноза",
    "prediction.patientNotice": "Ваш врач может пересмотреть ваши последние лабораторные результаты.",
    "dashboard.predictions": "Прогнозы отторжения",
    "dashboard.noHighRiskDesc": "Нет пациентов высокого риска",
    "dashboard.addFirstPatient": "Добавьте первого пациента",
    "dashboard.patientsAttention": "Пациенты, требующие внимания сегодня",
    "dashboard.priorityDisclaimer": "Баллы приоритета рассчитываются ИИ и предназначены для поддержки, а не замены клинических решений.",
    "dashboard.priority": "Приоритет",
    "dashboard.status": "Статус",
    "dashboard.reasons": "Причины",
    "dashboard.criticalCount": "срочных",
    "dashboard.reviewCount": "на проверку",
    "dashboard.allStable": "Все пациенты стабильны",
    "dashboard.noUrgent": "Нет пациентов, требующих срочного внимания",
    "schedule.title": "График анализов",
    "schedule.overdueTitle": "Пациенты с просроченными анализами",
    "schedule.lastLabDate": "Последний анализ",
    "schedule.expectedDate": "Ожидаемая дата",
    "schedule.status": "Статус",
    "schedule.overdue": "Просрочен",
    "schedule.dueSoon": "Скоро",
    "schedule.upcoming": "Предстоит",
    "schedule.completed": "Выполнен",
    "schedule.scheduledLab": "Запланированный лабораторный анализ",
    "schedule.overdueReminder": "Ваш запланированный анализ просрочен. Пожалуйста, загрузите результаты.",
    "schedule.dueSoonReminder": "Ваш следующий лабораторный анализ запланирован через 3 дня.",
    "schedule.medicalNote": "Регулярный лабораторный мониторинг необходим после трансплантации.",
    "schedule.disclaimer": "Приоритетные баллы основаны на ИИ и должны поддерживать, а не заменять клиническое решение.",
  },
  uz: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Bemor qo'shish",
    "nav.logout": "Chiqish",
    "nav.dashboard": "Boshqaruv",
    "nav.patients": "Bemorlar",
    "nav.medications": "Dorilar",
    "nav.alerts": "Ogohlantirishlar",
    "nav.reports": "Hisobotlar",
    "nav.analytics": "Analitika",
    "dashboard.title": "Boshqaruv paneli",
    "dashboard.subtitle": "Transplantatsiya bemorlarining umumiy ko'rinishi",
    "dashboard.totalPatients": "Jami bemorlar",
    "dashboard.highRisk": "Yuqori xavf",
    "dashboard.mediumRisk": "O'rta xavf",
    "dashboard.activeAlerts": "Faol ogohlantirishlar",
    "dashboard.riskDistribution": "Xavf taqsimoti",
    "dashboard.noPatients": "Hali bemorlar yo'q",
    "dashboard.highRiskPatients": "Yuqori xavfli bemorlar",
    "dashboard.noHighRisk": "Yuqori xavfli bemorlar yo'q",
    "dashboard.patient": "Bemor",
    "dashboard.organ": "Organ",
    "dashboard.daysPostTx": "Tx dan keyin kun",
    "dashboard.keyLab": "Lab. ma'lumot",
    "dashboard.risk": "Xavf",
    "login.title": "TransplantCare",
    "login.subtitle": "Transplantatsiya bemorlarini boshqarish tizimi",
    "login.signIn": "Kirish",
    "login.signUp": "Ro'yxatdan o'tish",
    "login.signInDesc": "Davom etish uchun ma'lumotlaringizni kiriting",
    "login.signUpDesc": "Hisob yaratish uchun ma'lumotlaringizni kiriting",
    "login.fullName": "To'liq ism",
    "login.email": "Elektron pochta",
    "login.password": "Parol",
    "login.createAccount": "Hisob yaratish",
    "login.alreadyHave": "Hisobingiz bormi?",
    "login.dontHave": "Hisobingiz yo'qmi?",
    "login.accountCreated": "Hisob yaratildi",
    "login.checkEmail": "Hisobingizni tasdiqlash uchun pochtangizni tekshiring.",
    "login.forgotPassword": "Parolni unutdingizmi?",
    "login.resetPassword": "Parolni tiklash",
    "login.resetDesc": "Parolni tiklash havolasini olish uchun emailingizni kiriting",
    "login.sendResetLink": "Havola yuborish",
    "login.resetSent": "Havola yuborildi",
    "login.resetSentDesc": "Parolni tiklash havolasi uchun pochtangizni tekshiring.",
    "login.backToLogin": "Kirishga qaytish",
    "login.newPassword": "Yangi parol",
    "login.confirmPassword": "Parolni tasdiqlang",
    "login.updatePassword": "Parolni yangilash",
    "login.passwordUpdated": "Parol yangilandi",
    "login.passwordUpdatedDesc": "Endi yangi parolingiz bilan kirishingiz mumkin.",
    "login.passwordMismatch": "Parollar mos kelmaydi",
    "role.welcome": "TransplantCare ga xush kelibsiz",
    "role.selectRole": "Davom etish uchun rolingizni tanlang",
    "role.doctor": "Shifokor / Tibbiy xodim",
    "role.doctorDesc": "Bemorlarni boshqarish, xavflarni tahlil qilish",
    "role.patient": "Bemor portali",
    "role.patientDesc": "Sog'lik holatingiz va tahlil natijalarini ko'ring",
    "role.support": "Qo'llab-quvvatlash",
    "role.supportDesc": "Foydalanuvchilarga yordam berish",
    "role.admin": "Administrator",
    "role.adminDesc": "Tizimni to'liq boshqarish",
    "add.selectOrgan": "Bemor qo'shish — Organ tanlash",
    "add.chooseType": "Transplantatsiya turini tanlang",
    "add.liverTransplant": "Jigar transplantatsiyasi",
    "add.kidneyTransplant": "Buyrak transplantatsiyasi",
    "add.liverDesc": "ALT, AST, Takrolimus, Bilirubin kuzatuvi",
    "add.kidneyDesc": "Kreatinin, SKF, Dializ tarixi kuzatuvi",
    "add.patientInfo": "Bemor ma'lumotlari",
    "add.fullName": "To'liq ism",
    "add.dob": "Tug'ilgan sana",
    "add.gender": "Jinsi",
    "add.male": "Erkak",
    "add.female": "Ayol",
    "add.other": "Boshqa",
    "add.transplantDetails": "Transplantatsiya tafsilotlari",
    "add.transplantNumber": "Transplantatsiya raqami",
    "add.transplantDate": "Transplantatsiya sanasi",
    "add.rejectionType": "Rad etish turi",
    "add.dialysisHistory": "Dializ tarixi",
    "add.yes": "Ha",
    "add.no": "Yo'q",
    "add.returnDialysisDate": "Dializ ga qaytish sanasi",
    "add.biopsyResult": "Biopsiya natijasi (ixtiyoriy)",
    "add.bloodInfo": "Qon guruhi ma'lumotlari",
    "add.bloodType": "Bemor qon guruhi",
    "add.donorBloodType": "Donor qon guruhi",
    "add.titerTherapy": "Titr pasaytirish terapiyasi o'tkazilgan",
    "add.bloodMismatchWarning": "Qon guruhi mos kelmayapti! Bu antitelo orqali rad etish (AMR) xavfini oshiradi.",
    "add.labResults": "Laboratoriya natijalari",
    "add.tacrolimus": "Takrolimus darajasi",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Umumiy bilirubin",
    "add.directBilirubin": "To'g'ridan-to'g'ri bilirubin",
    "add.creatinine": "Kreatinin",
    "add.egfr": "SKF",
    "add.proteinuria": "Proteinuriya",
    "add.potassium": "Kaliy",
    "add.save": "Bemorni saqlash",
    "add.patientAdded": "Bemor qo'shildi",
    "add.addLiver": "Jigar bemori qo'shish",
    "add.addKidney": "Buyrak bemori qo'shish",
    "detail.patientInfo": "Bemor ma'lumotlari",
    "detail.underReview": "Tibbiy nazorat ostida",
    "detail.latestLabs": "So'nggi tahlil natijalari",
    "detail.aiAdvisory": "AI maslahat va tekshiruv",
    "detail.approve": "Tasdiqlash",
    "detail.orOverride": "yoki o'zgartirish:",
    "detail.newRiskLevel": "Yangi xavf darajasi",
    "detail.overrideReason": "O'zgartirish uchun majburiy sabab...",
    "detail.overrideRisk": "Xavfni o'zgartirish",
    "detail.timeline": "Vaqt jadvali",
    "detail.noEvents": "Hodisalar yo'q",
    "detail.added": "Qo'shilgan",
    "detail.dob": "Tug'ilgan sana",
    "detail.riskApproved": "Xavf tasdiqlandi",
    "detail.provideReason": "Xavf darajasi va sababini kiriting",
    "detail.riskOverridden": "Xavf o'zgartirildi",
    "detail.addLab": "Tahlil qo'shish",
    "detail.addNewLab": "Yangi tahlil natijalari qo'shish",
    "detail.saveLab": "Natijalarni saqlash",
    "detail.labAdded": "Tahlil natijalari qo'shildi",
    "detail.labAddedEvent": "Yangi tahlil natijalari qayd etildi",
    "detail.date": "Sana",
    "detail.labHistory": "Tahlillar tarixi",
    "detail.editDate": "Sanani o'zgartirish",
    "detail.deleteLab": "O'chirish",
    "detail.confirmDeleteLab": "Bu tahlil natijasini o'chirasizmi?",
    "detail.confirmDeleteLabDesc": "Bu amalni qaytarib bo'lmaydi. Bog'liq xavf ma'lumotlari ham o'chiriladi.",
    "detail.labDeleted": "Tahlil natijasi o'chirildi",
    "detail.labDateUpdated": "Tahlil sanasi yangilandi",
    "home.healthStatus": "Sog'lik holatingiz",
    "home.name": "Ism",
    "home.organ": "Organ",
    "home.riskLevel": "Xavf darajasi",
    "home.highRiskWarning": "⚠️ Tibbiy nazorat ostida.",
    "home.careTimeline": "Davolash vaqt jadvali",
    "home.noEvents": "Hali hodisalar yo'q",
    "home.latestLabs": "So'nggi tahlil natijalari",
    "home.recorded": "Qayd etilgan",
    "home.noLinked": "Hisobingizga bemor yozuvi hali bog'lanmagan.",
    "home.loading": "Yuklanmoqda...",
    "common.loading": "Yuklanmoqda...",
    "common.error": "Xatolik",
    "common.optional": "Ixtiyoriy",
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.delete": "O'chirish",
    "common.edit": "Tahrirlash",
    "common.date": "Sana",
    "common.phone": "Telefon",
    "common.tests": "ta test",
    "upload.title": "Tahlil yuklash",
    "upload.uploadTitle": "Laboratoriya hisobotini yuklash",
    "upload.processing": "Hisobot qayta ishlanmoqda...",
    "upload.confirm": "Natijalarni tasdiqlang",
    "upload.description": "Lab hisobotingizning rasmi yoki faylini yuklang. Bir faylda bir nechta sanadagi natijalar bo'lsa, har biri alohida saqlanadi.",
    "upload.takePhoto": "Rasm olish",
    "upload.uploadFile": "Fayl yuklash",
    "upload.aiProcessing": "AI yordamida lab qiymatlari ajratilmoqda...",
    "upload.detectingDates": "Sanalar, maket va test nomlari aniqlanmoqda",
    "upload.datesDetected": "ta alohida sana aniqlandi — har biri alohida lab natijasi sifatida saqlanadi",
    "upload.dateLabel": "Sana:",
    "upload.enterDateManually": "Sanani qo'lda kiriting",
    "upload.dateNotDetected": "Sana aniqlanmadi",
    "upload.dateNotDetectedDesc": "Sana aniqlanmadi — qo'lda kiriting:",
    "upload.valuesFound": "ta qiymat topildi",
    "upload.needsVerification": "ta tekshirish kerak",
    "upload.lowConfidence": "Past ishonchlilik — tekshiring:",
    "upload.saveResults": "Natijalarni saqlash",
    "upload.confirmResults": "Natijalarni tasdiqlash",
    "upload.reupload": "Qayta yuklash",
    "upload.resultsSaved": "Natijalar saqlandi",
    "upload.verifyValues": "ta qiymat tekshirishni talab qiladi",
    "upload.lowConfidenceDesc": "Past ishonchlilikdagi qiymatlar ajratib ko'rsatilgan.",
    "upload.original": "Asl nusxa",
    "lab.noResults": "Tahlil natijalari mavjud emas",
    "lab.testName": "Test nomi",
    "lab.value": "Qiymat",
    "lab.unit": "Birlik",
    "lab.reference": "Norma",
    "lab.status": "Holat",
    "lab.normal": "Normal",
    "lab.high": "Yuqori",
    "lab.borderline": "Chegaraviy",
    "lab.noTrendData": "Trend ma'lumotlari mavjud emas",
    "lab.latestLabs": "Oxirgi tahlillar",
    "lab.labHistory": "Tahlillar tarixi",
    "lab.latest": "Oxirgi",
    "risk.score": "Xavf bahosi",
    "risk.calculating": "Hisoblanmoqda...",
    "risk.noLabData": "Tahlil natijalari kiritilmagan",
    "risk.factors": "Xavf omillari:",
    "risk.highDetected": "Yuqori xavf aniqlandi",
    "risk.mediumDetected": "O'rta xavf aniqlandi",
    "risk.explanation": "Nima uchun bu xavf darajasi",
    "risk.sinceLastTest": "oxirgi tahlildan beri",
    "risk.lastEvaluation": "Oxirgi baholash",
    "time.minAgo": "daqiqa oldin",
    "time.hourAgo": "soat oldin",
    "time.dayAgo": "kun oldin",
    "priority.highRisk": "Yuqori xavf darajasi (>80)",
    "priority.mediumRisk": "O'rtacha xavf darajasi",
    "priority.highLevel": "Yuqori xavf darajasi",
    "priority.newLab": "Yangi tahlil yuklandi (24 soat ichida)",
    "priority.notReviewed": "kun ko'rib chiqilmagan",
    "priority.neverReviewed": "Hech qachon ko'rib chiqilmagan",
    "priority.creatinineHigh": "Kreatinin yuqori",
    "priority.egfrLow": "eGFR past",
    "priority.potassiumAbnormal": "Kaliy og'ishi",
    "priority.altHigh": "ALT yuqori",
    "priority.astHigh": "AST yuqori",
    "priority.tacrolimusAbnormal": "Tacrolimus og'ishi",
    "priority.bilirubinHigh": "Bilirubin yuqori",
    "priority.cat_critical": "Zudlik bilan e'tibor",
    "priority.cat_review": "Ko'rib chiqish kerak",
    "priority.cat_stable": "Barqaror",
    "dashboard.allPatients": "Jami bemorlar",
    "schedule.onSchedule": "Jadval bo'yicha",
    "prediction.disclaimer": "Bu bashorat AI yordamida tuzilgan va tibbiy mutaxassis tomonidan ko'rib chiqilishi kerak.",
    "patientAlerts.title": "Ogohlantirishlar",
    "patientAlerts.markAllRead": "Barchasini o'qildi",
    "edit.title": "Bemor ma'lumotlarini tahrirlash",
    "edit.patientUpdated": "Bemor ma'lumotlari saqlandi",
    "edit.enterName": "Ismni kiriting",
    "edit.none": "Yo'q",
    "edit.acute": "O'tkir",
    "edit.chronic": "Surunkali",
    "profile.overview": "Umumiy",
    "profile.labResults": "Tahlillar",
    "profile.trends": "Trendlar",
    "profile.risk": "Xavf",
    "profile.timeline": "Vaqt jadvali",
    "profile.patientInfo": "Bemor ma'lumotlari",
    "profile.fullName": "To'liq ism",
    "profile.organType": "Organ turi",
    "profile.gender": "Jinsi",
    "profile.dob": "Tug'ilgan sana",
    "profile.transplantDate": "Transplantatsiya sanasi",
    "profile.transplant": "Transplantatsiya",
    "profile.highRiskWarning": "⚠️ Xavf darajangiz yuqori. Imkon qadar tezroq shifokoringizga murojaat qiling.",
    "profile.careTimeline": "Davolash vaqt jadvali",
    "profile.noEvents": "Hodisalar qayd etilmagan",
    "detail.patientNotFound": "Bemor topilmadi",
    "detail.confirmDelete": "Bemorni o'chirish",
    "detail.confirmDeleteDesc": "Haqiqatan ham bu bemorni o'chirmoqchimisiz? Bu amalni qaytarib bo'lmaydi.",
    "detail.patientDeleted": "Bemor o'chirildi",
    "detail.patientUpdated": "Bemor ma'lumotlari saqlandi",
    "analytics.title": "Analitika va statistika",
    "analytics.subtitle": "Milliy transplantatsiya statistikasi",
    "analytics.print": "Chop etish",
    "analytics.exportCSV": "CSV eksport",
    "analytics.filters": "Filtrlar",
    "analytics.allYears": "Barcha yillar",
    "analytics.allRegions": "Barcha hududlar",
    "analytics.allOrgans": "Barcha organlar",
    "analytics.reset": "Tozalash",
    "analytics.transplantsByYear": "Yillar bo'yicha transplantatsiyalar",
    "analytics.survivalTrends": "Yashash trendlari",
    "analytics.centerComparison": "Markazlar taqqoslash",
    "analytics.centerName": "Markaz nomi",
    "analytics.region": "Hudud",
    "analytics.total": "Jami",
    "analytics.kidney": "Buyrak",
    "analytics.liver": "Jigar",
    "analytics.oneYearSurvival": "1 yillik",
    "analytics.threeYearSurvival": "3 yillik",
    "analytics.tashkent": "Toshkent",
    "analytics.samarkand": "Samarqand",
    "analytics.vakhidovCenter": "Vohidov nomidagi Respublika markazi",
    "analytics.nephrologyCenter": "Nefrologiya markazi",
    "analytics.nationalMedicalCenter": "Milliy tibbiyot markazi",
    "analytics.childrenNationalCenter": "Bolalar milliy markazi",
    "reports.title": "Hisobotlar va byudjet",
    "reports.medications": "Dorilar",
    "reports.equipment": "Uskunalar",
    "reports.personnel": "Xodimlar",
    "reports.facilities": "Binolar",
    "reports.totalBudget": "Umumiy byudjet",
    "reports.spentYTD": "Sarflangan",
    "reports.remaining": "Qoldiq",
    "reports.patientsCovered": "Bemorlar",
    "reports.annualAllocation": "Yillik byudjet",
    "reports.patientTrends": "Bemor trendlari",
    "reports.patients": "Bemorlar",
    "reports.transplants": "Transplantatsiyalar",
    "reports.budgetAllocation": "Byudjet taqsimoti",
    "reports.departmentUtilization": "Bo'limlar bo'yicha foydalanish",
    "reports.availableReports": "Mavjud hisobotlar",
    "reports.generateNew": "Yangi hisobot",
    "reports.downloaded": "Hisobot yuklab olindi",
    "reports.generated": "Hisobot yaratildi",
    "reports.monthlyPatientRegistry": "Oylik bemor reestri",
    "reports.quarterlyTransplantStats": "Choraklik statistika",
    "reports.medicationUsageReport": "Dori foydalanish hisoboti",
    "reports.regionalDistribution": "Hududiy tahlil",
    "alerts.alertCenter": "Ogohlantirish markazi",
    "alerts.filter": "Filtr",
    "alerts.all": "Barchasi",
    "alerts.critical": "Kritik",
    "alerts.warning": "Ogohlantirish",
    "alerts.warnings": "Ogohlantirishlar",
    "alerts.info": "Ma'lumot",
    "alerts.unread": "O'qilmagan",
    "alerts.resolved": "Hal qilingan",
    "alerts.view": "Ko'rish",
    "alerts.noAlerts": "Ogohlantirishlar yo'q",
    "alerts.markRead": "O'qildi",
    "alerts.criticalLabResult": "Kritik tahlil natijasi",
    "alerts.medicationStockCritical": "Dori zahirasi kritik",
    "alerts.missedCheckin": "Dori qabuli o'tkazib yuborildi",
    "alerts.lowStock": "Kam zahira",
    "alerts.scheduledAppointment": "Rejalashtirilgan qabul",
    "alerts.labNormal": "Tahlillar norma",
    "medications.inventory": "Dori ombori",
    "medications.search": "Qidiruv...",
    "medications.totalMedications": "Jami dorilar",
    "medications.lowStock": "Kam zahira",
    "medications.criticalStock": "Kritik zahira",
    "medications.ordersPending": "Kutilayotgan buyurtmalar",
    "medications.medication": "Dori",
    "medications.category": "Kategoriya",
    "medications.currentStock": "Joriy zahira",
    "medications.stockLevel": "Zahira darajasi",
    "medications.monthlyUsage": "Oylik sarflanish",
    "medications.trend": "Trend",
    "medications.status": "Holat",
    "medications.critical": "Kritik",
    "medications.low": "Kam",
    "medications.inStock": "Mavjud",
    "medications.activeLabel": "Faol",
    "medications.inactiveLabel": "Nofaol",
    "medications.dosages": "Dozalar",
    "medications.frequency": "Chastota",
    "medications.noResults": "Natija topilmadi",
    "analytics.unknown": "Noma'lum",
    "patients.total": "Jami retsipiyentlar",
    "patients.alive": "Tirik",
    "patients.onDialysis": "Dializ da",
    "patients.deceased": "Vafot etgan",
    "patients.recipientsList": "Retsipiyentlar ro'yxati",
    "patients.export": "Eksport",
    "patients.newTransplant": "Yangi transplantatsiya",
    "patients.search": "Bemorlarni qidirish...",
    "patients.organ": "Organ",
    "patients.allOrgans": "Barcha organlar",
    "patients.allStatus": "Barcha holatlar",
    "patients.name": "Ism",
    "patients.ageGender": "Yosh/Jinsi",
    "patients.transplantDate": "Transplantatsiya sanasi",
    "patients.region": "Hudud",
    "patients.status": "Holat",
    "patients.riskScore": "Xavf bali",
    "med.title": "Dorilar",
    "med.subtitle": "Bemor dorilarini kuzatish va doza boshqaruvi",
    "med.addMedication": "Dori qo'shish",
    "med.medicationName": "Dori nomi",
    "med.dosage": "Dozasi",
    "med.frequency": "Qabul chastotasi",
    "med.startDate": "Boshlanish sanasi",
    "med.endDate": "Tugash sanasi",
    "med.notes": "Eslatmalar",
    "med.actions": "Amallar",
    "med.activeMeds": "Faol dorilar",
    "med.stoppedMeds": "To'xtatilgan",
    "med.totalChanges": "Doza o'zgarishlari",
    "med.changeHistory": "O'zgarishlar tarixi",
    "med.noMedications": "Hali dorilar qo'shilmagan",
    "med.noStoppedMeds": "To'xtatilgan dorilar yo'q",
    "med.noChanges": "Doza o'zgarishlari yo'q",
    "med.changeDosage": "Dozani o'zgartirish",
    "med.changeDosageTitle": "Dozani o'zgartirish",
    "med.currentDosage": "Joriy doza",
    "med.newDosage": "Yangi doza",
    "med.reason": "Sabab",
    "med.reasonPlaceholder": "Doza o'zgartirish sababi...",
    "med.dosageChanged": "Doza muvaffaqiyatli o'zgartirildi",
    "med.fillRequired": "Majburiy maydonlarni to'ldiring",
    "med.added": "Dori qo'shildi",
    "med.stop": "To'xtatish",
    "med.stopConfirm": "Dorini to'xtatishni tasdiqlaysizmi?",
    "med.stopDesc": "Haqiqatan ham bu dorini to'xtatmoqchimisiz?",
    "med.search": "Dorilarni qidirish...",
    "med.daily": "Kuniga bir marta",
    "med.twice_daily": "Kuniga ikki marta",
    "med.threeTimesDaily": "Kuniga uch marta",
    "med.three_times": "Kuniga uch marta",
    "med.weekly": "Haftada bir marta",
    "med.as_needed": "Kerak bo'lganda",
    "med.unknownMed": "Noma'lum dori",
    "med.myMedications": "Mening dorilarim",
    "med.selectMedication": "Dorini tanlang",
    "med.customMedication": "Boshqa (qo'lda kiritish)",
    "med.selectDosage": "Dozani tanlang",
    "med.customDosage": "Boshqa doza",
    "med.group": "Guruh",
    "medGroup.cni": "Kalsinevrin ingibitorlari (CNI)",
    "medGroup.antimetabolite": "Antimetabolitlar (MMF/MPA)",
    "medGroup.mtor": "mTOR ingibitorlari",
    "medGroup.corticosteroid": "Kortikosteroidlar",
    "medGroup.other": "Boshqalar",
    "patients.lowRisk": "Past xavf",
    "med.perMonth": "oy",
    "upload.labUploadedEvent": "Lab hisoboti OCR orqali yuklandi",
    "organ.liver": "Jigar",
    "organ.kidney": "Buyrak",
    "gender.male": "Erkak",
    "gender.female": "Ayol",
    "gender.other": "Boshqa",
    "risk.high": "YUQORI",
    "risk.medium": "O'RTA",
    "risk.low": "PAST",
    "flag.tacrolimus_low": "Takrolimus past",
    "flag.tacrolimus_high": "Takrolimus yuqori",
    "flag.alt_critical": "ALT kritik",
    "flag.alt_elevated": "ALT yuqori",
    "flag.ast_critical": "AST kritik",
    "flag.ast_elevated": "AST yuqori",
    "flag.bilirubin_critical": "Bilirubin kritik",
    "flag.bilirubin_elevated": "Bilirubin yuqori",
    "flag.retransplant": "Qayta transplantatsiya bemori",
    "flag.creatinine_critical": "Kreatinin kritik",
    "flag.creatinine_elevated": "Kreatinin yuqori",
    "flag.egfr_very_low": "SKF juda past",
    "flag.egfr_low": "SKF past",
    "flag.dialysis_history": "Dializ tarixi",
    "time.justNow": "hozirgina",
    "time.minutesAgo": "daqiqa oldin",
    "time.hoursAgo": "soat oldin",
    "time.daysAgo": "kun oldin",
    "month.jan": "Yan", "month.feb": "Fev", "month.mar": "Mar",
    "month.apr": "Apr", "month.may": "May", "month.jun": "Iyn",
    "month.jul": "Iyl", "month.aug": "Avg", "month.sep": "Sen",
    "month.oct": "Okt", "month.nov": "Noy", "month.dec": "Dek",
    "event.txAdded": "Transplantatsiya qo'shildi",
    "event.dialysisRecorded": "Dializ ga qaytish qayd etildi",
    "event.riskOverridden": "Xavf o'zgartirildi",
    "date.year": "Yil",
    "date.month": "Oy",
    "date.day": "Kun",
    "date.monthSuffix": "oy",
    "add.region": "Viloyat / Hudud",
    "add.district": "Tuman",
    "add.selectPlaceholder": "Tanlang...",
    "error.title": "Xatolik",
    "error.sessionExpired": "Sessiya muddati tugadi. Qayta kiring.",
    "error.invalidCredentials": "Login yoki parol noto'g'ri.",
    "error.emailNotConfirmed": "Email tasdiqlanmagan. Pochtangizni tekshiring.",
    "error.alreadyRegistered": "Bu email allaqachon ro'yxatdan o'tgan.",
    "error.duplicateKey": "Bu ma'lumot allaqachon mavjud.",
    "error.noPermission": "Sizda bu amalni bajarish uchun ruxsat yo'q.",
    "error.noInternet": "Internet aloqasi yo'q. Qayta urinib ko'ring.",
    "error.networkError": "Tarmoq xatosi. Internet aloqasini tekshiring.",
    "error.unexpected": "Kutilmagan xatolik yuz berdi. Qayta urinib ko'ring.",
    "error.unknown": "Noma'lum xatolik yuz berdi.",
    "translate.writtenIn": "Yozilgan til",
    "translate.translating": "Tarjima qilinmoqda...",
    "translate.noteLanguage": "Eslatma tili",
    "prediction.title": "Rad etish bashorati",
    "prediction.analyzing": "Trendlar tahlil qilinmoqda...",
    "prediction.currentRisk": "Joriy xavf",
    "prediction.prediction": "Bashorat",
    "prediction.timeframe": "Muddat",
    "prediction.reasons": "Bashorat sabablari",
    "prediction.noPrediction": "Bashorat uchun yetarli ma'lumot yo'q",
    "prediction.patientNotice": "Shifokoringiz yaqinda laboratoriya natijalaringizni ko'rib chiqishi mumkin.",
    "dashboard.predictions": "Rad etish bashoratlari",
    "dashboard.noHighRiskDesc": "Hozirda yuqori xavfli bemorlar yo'q",
    "dashboard.addFirstPatient": "Birinchi bemorni qo'shing",
    "dashboard.patientsAttention": "Bugun e'tibor talab qiladigan bemorlar",
    "dashboard.priorityDisclaimer": "Ustuvorlik ballari AI yordamida hisoblanadi va klinik qarorlarni qo'llab-quvvatlash uchun mo'ljallangan.",
    "dashboard.priority": "Ustuvorlik",
    "dashboard.status": "Holat",
    "dashboard.reasons": "Sabablar",
    "dashboard.criticalCount": "zudlik",
    "dashboard.reviewCount": "ko'rib chiqish",
    "dashboard.allStable": "Barcha bemorlar barqaror",
    "dashboard.noUrgent": "Hozirda zudlik talab qiladigan bemor yo'q",
    "schedule.title": "Tahlil jadvali",
    "schedule.overdueTitle": "Tahlili kechikkan bemorlar",
    "schedule.lastLabDate": "So'nggi tahlil",
    "schedule.expectedDate": "Kutilgan sana",
    "schedule.status": "Holat",
    "schedule.overdue": "Kechikkan",
    "schedule.dueSoon": "Yaqinda",
    "schedule.upcoming": "Rejalashtirilgan",
    "schedule.completed": "Bajarilgan",
    "schedule.scheduledLab": "Rejalashtirilgan laboratoriya tahlili",
    "schedule.overdueReminder": "Rejalashtirilgan tahlil muddati o'tgan. Iltimos, natijalaringizni yuklang.",
    "schedule.dueSoonReminder": "Keyingi laboratoriya tahlilingiz 3 kun ichida rejalashtirilgan.",
    "schedule.medicalNote": "Transplantatsiya operatsiyasidan keyin muntazam laboratoriya monitoringi zarur.",
    "schedule.disclaimer": "Ustuvorlik ballari AI yordamida hisoblanadi va klinik qarorni qo'llab-quvvatlaydi, lekin almashtirmaydi.",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-lang");
    return (saved as Language) || "en";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("app-lang", newLang);
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
