import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ru" | "uz";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Add Patient",
    "nav.logout": "Logout",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Transplant patient overview",
    "dashboard.totalPatients": "Total Patients",
    "dashboard.highRisk": "High Risk",
    "dashboard.mediumRisk": "Medium Risk",
    "dashboard.activeAlerts": "Active Alerts",
    "dashboard.riskDistribution": "Risk Distribution",
    "dashboard.noPatients": "No patients yet",
    "dashboard.highRiskPatients": "High-Risk Patients",
    "dashboard.noHighRisk": "No high-risk patients",
    "dashboard.patient": "Patient",
    "dashboard.organ": "Organ",
    "dashboard.daysPostTx": "Days Post-Tx",
    "dashboard.keyLab": "Key Lab",
    "dashboard.risk": "Risk",
    "login.title": "TransplantCare",
    "login.subtitle": "Transplant patient management system",
    "login.signIn": "Sign in",
    "login.signUp": "Create account",
    "login.signInDesc": "Enter your credentials to continue",
    "login.signUpDesc": "Enter your details to create an account",
    "login.fullName": "Full Name",
    "login.email": "Email",
    "login.password": "Password",
    "login.createAccount": "Create Account",
    "login.alreadyHave": "Already have an account?",
    "login.dontHave": "Don't have an account?",
    "login.accountCreated": "Account created",
    "login.checkEmail": "Please check your email to verify your account.",
    "login.forgotPassword": "Forgot password?",
    "login.resetPassword": "Reset Password",
    "login.resetDesc": "Enter your email to receive a password reset link",
    "login.sendResetLink": "Send Reset Link",
    "login.resetSent": "Reset link sent",
    "login.resetSentDesc": "Check your email for a password reset link.",
    "login.backToLogin": "Back to login",
    "login.newPassword": "New Password",
    "login.confirmPassword": "Confirm Password",
    "login.updatePassword": "Update Password",
    "login.passwordUpdated": "Password updated",
    "login.passwordUpdatedDesc": "You can now sign in with your new password.",
    "login.passwordMismatch": "Passwords do not match",
    "role.welcome": "Welcome to TransplantCare",
    "role.selectRole": "Select your role to continue",
    "role.doctor": "Doctor / Healthcare Provider",
    "role.doctorDesc": "Manage patients, review risks, and oversee transplant care",
    "role.patient": "Patient Portal",
    "role.patientDesc": "View your health status, lab results, and care timeline",
    "role.support": "Support",
    "role.supportDesc": "Help users with issues and manage support requests",
    "role.admin": "Administrator",
    "role.adminDesc": "Full system management, users and settings",
    "add.selectOrgan": "Add Patient — Select Organ",
    "add.chooseType": "Choose the transplant type",
    "add.liverTransplant": "Liver Transplant",
    "add.kidneyTransplant": "Kidney Transplant",
    "add.liverDesc": "ALT, AST, Tacrolimus, Bilirubin tracking",
    "add.kidneyDesc": "Creatinine, eGFR, Dialysis history tracking",
    "add.patientInfo": "Patient Information",
    "add.fullName": "Full Name",
    "add.dob": "Date of Birth",
    "add.gender": "Gender",
    "add.male": "Male",
    "add.female": "Female",
    "add.other": "Other",
    "add.transplantDetails": "Transplant Details",
    "add.transplantNumber": "Transplant Number",
    "add.transplantDate": "Transplant Date",
    "add.rejectionType": "Rejection Type",
    "add.dialysisHistory": "Dialysis History",
    "add.yes": "Yes",
    "add.no": "No",
    "add.returnDialysisDate": "Return to Dialysis Date",
    "add.biopsyResult": "Biopsy Result (optional)",
    "add.labResults": "Laboratory Results",
    "add.tacrolimus": "Tacrolimus Level",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Total Bilirubin",
    "add.directBilirubin": "Direct Bilirubin",
    "add.creatinine": "Creatinine",
    "add.egfr": "eGFR",
    "add.proteinuria": "Proteinuria",
    "add.potassium": "Potassium",
    "add.save": "Save Patient",
    "add.patientAdded": "Patient added",
    "add.addLiver": "Add Liver Patient",
    "add.addKidney": "Add Kidney Patient",
    "detail.patientInfo": "Patient Information",
    "detail.underReview": "Under medical review",
    "detail.latestLabs": "Latest Lab Results",
    "detail.aiAdvisory": "AI Advisory & Review",
    "detail.approve": "Approve",
    "detail.orOverride": "or override:",
    "detail.newRiskLevel": "New risk level",
    "detail.overrideReason": "Mandatory reason for override...",
    "detail.overrideRisk": "Override Risk",
    "detail.timeline": "Timeline",
    "detail.noEvents": "No events",
    "detail.added": "Added",
    "detail.dob": "Date of Birth",
    "detail.riskApproved": "Risk approved",
    "detail.provideReason": "Please provide a risk level and reason",
    "detail.riskOverridden": "Risk overridden",
    "detail.addLab": "Add Lab",
    "detail.addNewLab": "Add New Lab Results",
    "detail.saveLab": "Save Lab Results",
    "detail.labAdded": "Lab results added",
    "detail.labAddedEvent": "New lab results recorded",
    "detail.date": "Date",
    "detail.labHistory": "Lab Results History",
    "home.healthStatus": "Your Health Status",
    "home.name": "Name",
    "home.organ": "Organ",
    "home.riskLevel": "Risk Level",
    "home.highRiskWarning": "⚠️ Under medical review. Your care team is monitoring your status.",
    "home.careTimeline": "Care Timeline",
    "home.noEvents": "No events yet",
    "home.latestLabs": "Latest Lab Results",
    "home.recorded": "Recorded",
    "home.noLinked": "No patient record linked to your account yet. Please contact your healthcare provider.",
    "home.loading": "Loading...",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.optional": "Optional",
  },
  ru: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Добавить пациента",
    "nav.logout": "Выход",
    "dashboard.title": "Панель управления",
    "dashboard.subtitle": "Обзор пациентов с трансплантацией",
    "dashboard.totalPatients": "Всего пациентов",
    "dashboard.highRisk": "Высокий риск",
    "dashboard.mediumRisk": "Средний риск",
    "dashboard.activeAlerts": "Активные оповещения",
    "dashboard.riskDistribution": "Распределение рисков",
    "dashboard.noPatients": "Пациентов пока нет",
    "dashboard.highRiskPatients": "Пациенты высокого риска",
    "dashboard.noHighRisk": "Нет пациентов высокого риска",
    "dashboard.patient": "Пациент",
    "dashboard.organ": "Орган",
    "dashboard.daysPostTx": "Дней после Тх",
    "dashboard.keyLab": "Лаб. данные",
    "dashboard.risk": "Риск",
    "login.title": "TransplantCare",
    "login.subtitle": "Система управления пациентами с трансплантацией",
    "login.signIn": "Войти",
    "login.signUp": "Создать аккаунт",
    "login.signInDesc": "Введите данные для входа",
    "login.signUpDesc": "Введите данные для создания аккаунта",
    "login.fullName": "Полное имя",
    "login.email": "Электронная почта",
    "login.password": "Пароль",
    "login.createAccount": "Создать аккаунт",
    "login.alreadyHave": "Уже есть аккаунт?",
    "login.dontHave": "Нет аккаунта?",
    "login.accountCreated": "Аккаунт создан",
    "login.checkEmail": "Проверьте почту для подтверждения.",
    "login.forgotPassword": "Забыли пароль?",
    "login.resetPassword": "Сброс пароля",
    "login.resetDesc": "Введите email для получения ссылки сброса пароля",
    "login.sendResetLink": "Отправить ссылку",
    "login.resetSent": "Ссылка отправлена",
    "login.resetSentDesc": "Проверьте почту для ссылки сброса пароля.",
    "login.backToLogin": "Назад к входу",
    "login.newPassword": "Новый пароль",
    "login.confirmPassword": "Подтвердите пароль",
    "login.updatePassword": "Обновить пароль",
    "login.passwordUpdated": "Пароль обновлён",
    "login.passwordUpdatedDesc": "Теперь вы можете войти с новым паролем.",
    "login.passwordMismatch": "Пароли не совпадают",
    "role.welcome": "Добро пожаловать в TransplantCare",
    "role.selectRole": "Выберите роль для продолжения",
    "role.doctor": "Врач / Медицинский работник",
    "role.doctorDesc": "Управление пациентами, анализ рисков и контроль трансплантации",
    "role.patient": "Портал пациента",
    "role.patientDesc": "Просмотр состояния здоровья, результатов анализов и хронологии лечения",
    "role.support": "Поддержка",
    "role.supportDesc": "Помощь пользователям и управление запросами поддержки",
    "role.admin": "Администратор",
    "role.adminDesc": "Полное управление системой, пользователями и настройками",
    "add.selectOrgan": "Добавить пациента — Выбор органа",
    "add.chooseType": "Выберите тип трансплантации",
    "add.liverTransplant": "Трансплантация печени",
    "add.kidneyTransplant": "Трансплантация почки",
    "add.liverDesc": "Отслеживание ALT, AST, Такролимус, Билирубин",
    "add.kidneyDesc": "Отслеживание Креатинин, СКФ, История диализа",
    "add.patientInfo": "Информация о пациенте",
    "add.fullName": "Полное имя",
    "add.dob": "Дата рождения",
    "add.gender": "Пол",
    "add.male": "Мужской",
    "add.female": "Женский",
    "add.other": "Другой",
    "add.transplantDetails": "Детали трансплантации",
    "add.transplantNumber": "Номер трансплантации",
    "add.transplantDate": "Дата трансплантации",
    "add.rejectionType": "Тип отторжения",
    "add.dialysisHistory": "История диализа",
    "add.yes": "Да",
    "add.no": "Нет",
    "add.returnDialysisDate": "Дата возвращения на диализ",
    "add.biopsyResult": "Результат биопсии (необязательно)",
    "add.labResults": "Лабораторные результаты",
    "add.tacrolimus": "Уровень такролимуса",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Общий билирубин",
    "add.directBilirubin": "Прямой билирубин",
    "add.creatinine": "Креатинин",
    "add.egfr": "СКФ",
    "add.proteinuria": "Протеинурия",
    "add.potassium": "Калий",
    "add.save": "Сохранить пациента",
    "add.patientAdded": "Пациент добавлен",
    "add.addLiver": "Добавить пациента (Печень)",
    "add.addKidney": "Добавить пациента (Почка)",
    "detail.patientInfo": "Информация о пациенте",
    "detail.underReview": "На медицинском контроле",
    "detail.latestLabs": "Последние результаты анализов",
    "detail.aiAdvisory": "ИИ-консультация и проверка",
    "detail.approve": "Утвердить",
    "detail.orOverride": "или переопределить:",
    "detail.newRiskLevel": "Новый уровень риска",
    "detail.overrideReason": "Обязательная причина переопределения...",
    "detail.overrideRisk": "Переопределить риск",
    "detail.timeline": "Хронология",
    "detail.noEvents": "Нет событий",
    "detail.added": "Добавлен",
    "detail.dob": "Дата рождения",
    "detail.riskApproved": "Риск утверждён",
    "detail.provideReason": "Укажите уровень риска и причину",
    "detail.riskOverridden": "Риск переопределён",
    "detail.addLab": "Добавить анализ",
    "detail.addNewLab": "Добавить новые результаты анализов",
    "detail.saveLab": "Сохранить результаты",
    "detail.labAdded": "Результаты анализов добавлены",
    "detail.labAddedEvent": "Записаны новые результаты анализов",
    "detail.date": "Дата",
    "detail.labHistory": "История анализов",
    "home.healthStatus": "Ваше состояние здоровья",
    "home.name": "Имя",
    "home.organ": "Орган",
    "home.riskLevel": "Уровень риска",
    "home.highRiskWarning": "⚠️ На медицинском контроле. Ваша команда следит за вашим состоянием.",
    "home.careTimeline": "Хронология лечения",
    "home.noEvents": "Пока нет событий",
    "home.latestLabs": "Последние результаты анализов",
    "home.recorded": "Записано",
    "home.noLinked": "Запись пациента ещё не привязана к вашему аккаунту. Обратитесь к вашему лечащему врачу.",
    "home.loading": "Загрузка...",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.optional": "Необязательно",
  },
  uz: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Bemor qo'shish",
    "nav.logout": "Chiqish",
    "dashboard.title": "Boshqaruv paneli",
    "dashboard.subtitle": "Transplantatsiya bemorlarining umumiy ko'rinishi",
    "dashboard.totalPatients": "Jami bemorlar",
    "dashboard.highRisk": "Yuqori xavf",
    "dashboard.mediumRisk": "O'rta xavf",
    "dashboard.activeAlerts": "Faol ogohlantirishlar",
    "dashboard.riskDistribution": "Xavf taqsimoti",
    "dashboard.noPatients": "Hali bemorlar yo'q",
    "dashboard.highRiskPatients": "Yuqori xavfli bemorlar",
    "dashboard.noHighRisk": "Yuqori xavfli bemorlar yo'q",
    "dashboard.patient": "Bemor",
    "dashboard.organ": "Organ",
    "dashboard.daysPostTx": "Tx dan keyin kun",
    "dashboard.keyLab": "Lab. ma'lumot",
    "dashboard.risk": "Xavf",
    "login.title": "TransplantCare",
    "login.subtitle": "Transplantatsiya bemorlarini boshqarish tizimi",
    "login.signIn": "Kirish",
    "login.signUp": "Ro'yxatdan o'tish",
    "login.signInDesc": "Davom etish uchun ma'lumotlaringizni kiriting",
    "login.signUpDesc": "Hisob yaratish uchun ma'lumotlaringizni kiriting",
    "login.fullName": "To'liq ism",
    "login.email": "Elektron pochta",
    "login.password": "Parol",
    "login.createAccount": "Hisob yaratish",
    "login.alreadyHave": "Hisobingiz bormi?",
    "login.dontHave": "Hisobingiz yo'qmi?",
    "login.accountCreated": "Hisob yaratildi",
    "login.checkEmail": "Hisobingizni tasdiqlash uchun pochtangizni tekshiring.",
    "login.forgotPassword": "Parolni unutdingizmi?",
    "login.resetPassword": "Parolni tiklash",
    "login.resetDesc": "Parolni tiklash havolasini olish uchun emailingizni kiriting",
    "login.sendResetLink": "Havola yuborish",
    "login.resetSent": "Havola yuborildi",
    "login.resetSentDesc": "Parolni tiklash havolasi uchun pochtangizni tekshiring.",
    "login.backToLogin": "Kirishga qaytish",
    "login.newPassword": "Yangi parol",
    "login.confirmPassword": "Parolni tasdiqlang",
    "login.updatePassword": "Parolni yangilash",
    "login.passwordUpdated": "Parol yangilandi",
    "login.passwordUpdatedDesc": "Endi yangi parolingiz bilan kirishingiz mumkin.",
    "login.passwordMismatch": "Parollar mos kelmaydi",
    "role.welcome": "TransplantCare ga xush kelibsiz",
    "role.selectRole": "Davom etish uchun rolingizni tanlang",
    "role.doctor": "Shifokor / Tibbiy xodim",
    "role.doctorDesc": "Bemorlarni boshqarish, xavflarni tahlil qilish",
    "role.patient": "Bemor portali",
    "role.patientDesc": "Sog'lik holatingiz va tahlil natijalarini ko'ring",
    "role.support": "Qo'llab-quvvatlash",
    "role.supportDesc": "Foydalanuvchilarga yordam berish",
    "role.admin": "Administrator",
    "role.adminDesc": "Tizimni to'liq boshqarish",
    "add.selectOrgan": "Bemor qo'shish — Organ tanlash",
    "add.chooseType": "Transplantatsiya turini tanlang",
    "add.liverTransplant": "Jigar transplantatsiyasi",
    "add.kidneyTransplant": "Buyrak transplantatsiyasi",
    "add.liverDesc": "ALT, AST, Takrolimus, Bilirubin kuzatuvi",
    "add.kidneyDesc": "Kreatinin, SKF, Dializ tarixi kuzatuvi",
    "add.patientInfo": "Bemor ma'lumotlari",
    "add.fullName": "To'liq ism",
    "add.dob": "Tug'ilgan sana",
    "add.gender": "Jinsi",
    "add.male": "Erkak",
    "add.female": "Ayol",
    "add.other": "Boshqa",
    "add.transplantDetails": "Transplantatsiya tafsilotlari",
    "add.transplantNumber": "Transplantatsiya raqami",
    "add.transplantDate": "Transplantatsiya sanasi",
    "add.rejectionType": "Rad etish turi",
    "add.dialysisHistory": "Dializ tarixi",
    "add.yes": "Ha",
    "add.no": "Yo'q",
    "add.returnDialysisDate": "Dializ ga qaytish sanasi",
    "add.biopsyResult": "Biopsiya natijasi (ixtiyoriy)",
    "add.labResults": "Laboratoriya natijalari",
    "add.tacrolimus": "Takrolimus darajasi",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Umumiy bilirubin",
    "add.directBilirubin": "To'g'ridan-to'g'ri bilirubin",
    "add.creatinine": "Kreatinin",
    "add.egfr": "SKF",
    "add.proteinuria": "Proteinuriya",
    "add.potassium": "Kaliy",
    "add.save": "Bemorni saqlash",
    "add.patientAdded": "Bemor qo'shildi",
    "add.addLiver": "Jigar bemori qo'shish",
    "add.addKidney": "Buyrak bemori qo'shish",
    "detail.patientInfo": "Bemor ma'lumotlari",
    "detail.underReview": "Tibbiy nazorat ostida",
    "detail.latestLabs": "So'nggi tahlil natijalari",
    "detail.aiAdvisory": "AI maslahat va tekshiruv",
    "detail.approve": "Tasdiqlash",
    "detail.orOverride": "yoki o'zgartirish:",
    "detail.newRiskLevel": "Yangi xavf darajasi",
    "detail.overrideReason": "O'zgartirish uchun majburiy sabab...",
    "detail.overrideRisk": "Xavfni o'zgartirish",
    "detail.timeline": "Vaqt jadvali",
    "detail.noEvents": "Hodisalar yo'q",
    "detail.added": "Qo'shilgan",
    "detail.dob": "Tug'ilgan sana",
    "detail.riskApproved": "Xavf tasdiqlandi",
    "detail.provideReason": "Xavf darajasi va sababini kiriting",
    "detail.riskOverridden": "Xavf o'zgartirildi",
    "detail.addLab": "Tahlil qo'shish",
    "detail.addNewLab": "Yangi tahlil natijalari qo'shish",
    "detail.saveLab": "Natijalarni saqlash",
    "detail.labAdded": "Tahlil natijalari qo'shildi",
    "detail.labAddedEvent": "Yangi tahlil natijalari qayd etildi",
    "detail.date": "Sana",
    "detail.labHistory": "Tahlillar tarixi",
    "home.healthStatus": "Sog'lik holatingiz",
    "home.name": "Ism",
    "home.organ": "Organ",
    "home.riskLevel": "Xavf darajasi",
    "home.highRiskWarning": "⚠️ Tibbiy nazorat ostida.",
    "home.careTimeline": "Davolash vaqt jadvali",
    "home.noEvents": "Hali hodisalar yo'q",
    "home.latestLabs": "So'nggi tahlil natijalari",
    "home.recorded": "Qayd etilgan",
    "home.noLinked": "Hisobingizga bemor yozuvi hali bog'lanmagan.",
    "home.loading": "Yuklanmoqda...",
    "common.loading": "Yuklanmoqda...",
    "common.error": "Xatolik",
    "common.optional": "Ixtiyoriy",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-lang");
    return (saved as Language) || "en";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("app-lang", newLang);
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}