import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ru" | "uz";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Add Patient",
    "nav.logout": "Logout",
    "nav.dashboard": "Dashboard",
    "nav.patients": "Patients",
    "nav.medications": "Medications",
    "nav.alerts": "Alerts",
    "nav.reports": "Reports",
    "nav.analytics": "Analytics",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Transplant patient overview",
    "dashboard.totalPatients": "Total Patients",
    "dashboard.highRisk": "High Risk",
    "dashboard.mediumRisk": "Medium Risk",
    "dashboard.activeAlerts": "Active Alerts",
    "dashboard.riskDistribution": "Risk Distribution",
    "dashboard.noPatients": "No patients yet",
    "dashboard.highRiskPatients": "High-Risk Patients",
    "dashboard.noHighRisk": "No high-risk patients",
    "dashboard.patient": "Patient",
    "dashboard.organ": "Organ",
    "dashboard.daysPostTx": "Days Post-Tx",
    "dashboard.keyLab": "Key Lab",
    "dashboard.risk": "Risk",
    "login.title": "TransplantCare",
    "login.subtitle": "Transplant patient management system",
    "login.signIn": "Sign in",
    "login.signUp": "Create account",
    "login.signInDesc": "Enter your credentials to continue",
    "login.signUpDesc": "Enter your details to create an account",
    "login.fullName": "Full Name",
    "login.email": "Email",
    "login.password": "Password",
    "login.createAccount": "Create Account",
    "login.alreadyHave": "Already have an account?",
    "login.dontHave": "Don't have an account?",
    "login.accountCreated": "Account created",
    "login.checkEmail": "Please check your email to verify your account.",
    "login.forgotPassword": "Forgot password?",
    "login.resetPassword": "Reset Password",
    "login.resetDesc": "Enter your email to receive a password reset link",
    "login.sendResetLink": "Send Reset Link",
    "login.resetSent": "Reset link sent",
    "login.resetSentDesc": "Check your email for a password reset link.",
    "login.backToLogin": "Back to login",
    "login.newPassword": "New Password",
    "login.confirmPassword": "Confirm Password",
    "login.updatePassword": "Update Password",
    "login.passwordUpdated": "Password updated",
    "login.passwordUpdatedDesc": "You can now sign in with your new password.",
    "login.passwordMismatch": "Passwords do not match",
    "role.welcome": "Welcome to TransplantCare",
    "role.selectRole": "Select your role to continue",
    "role.doctor": "Doctor / Healthcare Provider",
    "role.doctorDesc": "Manage patients, review risks, and oversee transplant care",
    "role.patient": "Patient Portal",
    "role.patientDesc": "View your health status, lab results, and care timeline",
    "role.support": "Support",
    "role.supportDesc": "Help users with issues and manage support requests",
    "role.admin": "Administrator",
    "role.adminDesc": "Full system management, users and settings",
    "add.selectOrgan": "Add Patient — Select Organ",
    "add.chooseType": "Choose the transplant type",
    "add.liverTransplant": "Liver Transplant",
    "add.kidneyTransplant": "Kidney Transplant",
    "add.liverDesc": "ALT, AST, Tacrolimus, Bilirubin tracking",
    "add.kidneyDesc": "Creatinine, eGFR, Dialysis history tracking",
    "add.patientInfo": "Patient Information",
    "add.fullName": "Full Name",
    "add.dob": "Date of Birth",
    "add.gender": "Gender",
    "add.male": "Male",
    "add.female": "Female",
    "add.other": "Other",
    "add.transplantDetails": "Transplant Details",
    "add.transplantNumber": "Transplant Number",
    "add.transplantDate": "Transplant Date",
    "add.rejectionType": "Rejection Type",
    "add.dialysisHistory": "Dialysis History",
    "add.yes": "Yes",
    "add.no": "No",
    "add.returnDialysisDate": "Return to Dialysis Date",
    "add.biopsyResult": "Biopsy Result (optional)",
    "add.labResults": "Laboratory Results",
    "add.tacrolimus": "Tacrolimus Level",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Total Bilirubin",
    "add.directBilirubin": "Direct Bilirubin",
    "add.creatinine": "Creatinine",
    "add.egfr": "eGFR",
    "add.proteinuria": "Proteinuria",
    "add.potassium": "Potassium",
    "add.save": "Save Patient",
    "add.patientAdded": "Patient added",
    "add.addLiver": "Add Liver Patient",
    "add.addKidney": "Add Kidney Patient",
    "detail.patientInfo": "Patient Information",
    "detail.underReview": "Under medical review",
    "detail.latestLabs": "Latest Lab Results",
    "detail.aiAdvisory": "AI Advisory & Review",
    "detail.approve": "Approve",
    "detail.orOverride": "or override:",
    "detail.newRiskLevel": "New risk level",
    "detail.overrideReason": "Mandatory reason for override...",
    "detail.overrideRisk": "Override Risk",
    "detail.timeline": "Timeline",
    "detail.noEvents": "No events",
    "detail.added": "Added",
    "detail.dob": "Date of Birth",
    "detail.riskApproved": "Risk approved",
    "detail.provideReason": "Please provide a risk level and reason",
    "detail.riskOverridden": "Risk overridden",
    "detail.addLab": "Add Lab",
    "detail.addNewLab": "Add New Lab Results",
    "detail.saveLab": "Save Lab Results",
    "detail.labAdded": "Lab results added",
    "detail.labAddedEvent": "New lab results recorded",
    "detail.date": "Date",
    "detail.labHistory": "Lab Results History",
    "home.healthStatus": "Your Health Status",
    "home.name": "Name",
    "home.organ": "Organ",
    "home.riskLevel": "Risk Level",
    "home.highRiskWarning": "⚠️ Under medical review. Your care team is monitoring your status.",
    "home.careTimeline": "Care Timeline",
    "home.noEvents": "No events yet",
    "home.latestLabs": "Latest Lab Results",
    "home.recorded": "Recorded",
    "home.noLinked": "No patient record linked to your account yet. Please contact your healthcare provider.",
    "home.loading": "Loading...",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.optional": "Optional",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.date": "Date",
    "common.phone": "Phone",
    "common.tests": "tests",
    // Lab Upload
    "upload.title": "Upload Lab Report",
    "upload.uploadTitle": "Upload Laboratory Report",
    "upload.processing": "Processing report...",
    "upload.confirm": "Confirm Results",
    "upload.description": "Upload a photo or file of your lab report. If one file has results from multiple dates, each will be saved separately.",
    "upload.takePhoto": "Take Photo",
    "upload.uploadFile": "Upload File",
    "upload.aiProcessing": "Extracting lab values with AI...",
    "upload.detectingDates": "Detecting dates, layout and test names",
    "upload.datesDetected": "separate dates detected — each will be saved as a separate lab result",
    "upload.dateLabel": "Date:",
    "upload.enterDateManually": "Enter date manually",
    "upload.dateNotDetected": "Date not detected",
    "upload.dateNotDetectedDesc": "Date not detected — enter manually:",
    "upload.valuesFound": "values found",
    "upload.needsVerification": "needs verification",
    "upload.lowConfidence": "Low confidence — verify:",
    "upload.saveResults": "Save results",
    "upload.confirmResults": "Confirm results",
    "upload.reupload": "Re-upload",
    "upload.resultsSaved": "Results saved for dates",
    "upload.verifyValues": "values need verification",
    "upload.lowConfidenceDesc": "Low confidence values are highlighted.",
    "upload.original": "Original",
    // Lab Results Table
    "lab.noResults": "No lab results available",
    "lab.testName": "Test Name",
    "lab.value": "Value",
    "lab.unit": "Unit",
    "lab.reference": "Reference",
    "lab.status": "Status",
    "lab.normal": "Normal",
    "lab.high": "High",
    "lab.borderline": "Borderline",
    "lab.noTrendData": "No trend data available",
    "lab.latestLabs": "Latest Labs",
    "lab.labHistory": "Lab History",
    "lab.latest": "Latest",
    // Risk Score
    "risk.score": "Risk Score",
    "risk.calculating": "Calculating...",
    "risk.noLabData": "No lab results entered",
    "risk.factors": "Risk factors:",
    // Patient Alerts
    "patientAlerts.title": "Alerts",
    "patientAlerts.markAllRead": "Mark all read",
    // Edit Patient
    "edit.title": "Edit Patient Information",
    "edit.patientUpdated": "Patient information saved",
    "edit.enterName": "Enter name",
    "edit.none": "None",
    "edit.acute": "Acute",
    "edit.chronic": "Chronic",
    // Patient Profile
    "profile.overview": "Overview",
    "profile.labResults": "Lab Results",
    "profile.trends": "Trends",
    "profile.risk": "Risk",
    "profile.timeline": "Timeline",
    "profile.patientInfo": "Patient Information",
    "profile.fullName": "Full Name",
    "profile.organType": "Organ Type",
    "profile.gender": "Gender",
    "profile.dob": "Date of Birth",
    "profile.transplantDate": "Transplant Date",
    "profile.transplant": "Transplant",
    "profile.highRiskWarning": "⚠️ Your risk level is elevated. Please consult your doctor as soon as possible.",
    "profile.careTimeline": "Care Timeline",
    "profile.noEvents": "No events recorded",
    // Detail
    "detail.patientNotFound": "Patient not found",
    "detail.confirmDelete": "Delete Patient",
    "detail.confirmDeleteDesc": "Are you sure you want to delete this patient? This action cannot be undone.",
    "detail.patientDeleted": "Patient deleted",
    "detail.patientUpdated": "Patient information saved",
    // Analytics
    "analytics.title": "Analytics & Statistics",
    "analytics.subtitle": "National transplant statistics and center comparison",
    "analytics.print": "Print",
    "analytics.exportCSV": "Export CSV",
    "analytics.filters": "Filters",
    "analytics.allYears": "All Years",
    "analytics.allRegions": "All Regions",
    "analytics.allOrgans": "All Organs",
    "analytics.reset": "Reset",
    "analytics.transplantsByYear": "Transplants by Year",
    "analytics.survivalTrends": "National Survival Trends",
    "analytics.centerComparison": "Transplant Center Comparison",
    "analytics.centerName": "Center Name",
    "analytics.region": "Region",
    "analytics.total": "Total",
    "analytics.kidney": "Kidney",
    "analytics.liver": "Liver",
    "analytics.oneYearSurvival": "1Y Survival",
    "analytics.threeYearSurvival": "3Y Survival",
    "analytics.tashkent": "Tashkent",
    "analytics.samarkand": "Samarkand",
    "analytics.vakhidovCenter": "Vakhidov Republican Center",
    "analytics.nephrologyCenter": "Nephrology Center",
    "analytics.nationalMedicalCenter": "National Medical Center",
    "analytics.childrenNationalCenter": "Children's National Center",
    // Reports
    "reports.title": "Reports & Budget",
    "reports.medications": "Medications",
    "reports.equipment": "Equipment",
    "reports.personnel": "Personnel",
    "reports.facilities": "Facilities",
    "reports.totalBudget": "Total Budget",
    "reports.spentYTD": "Spent YTD",
    "reports.remaining": "Remaining",
    "reports.patientsCovered": "Patients Covered",
    "reports.annualAllocation": "Annual allocation",
    "reports.patientTrends": "Patient & Transplant Trends",
    "reports.patients": "Patients",
    "reports.transplants": "Transplants",
    "reports.budgetAllocation": "Budget Allocation",
    "reports.departmentUtilization": "Department Utilization",
    "reports.availableReports": "Available Reports",
    "reports.generateNew": "Generate New",
    "reports.monthlyPatientRegistry": "Monthly Patient Registry",
    "reports.quarterlyTransplantStats": "Quarterly Transplant Stats",
    "reports.medicationUsageReport": "Medication Usage Report",
    "reports.regionalDistribution": "Regional Distribution Analysis",
    // Alerts
    "alerts.alertCenter": "Alert Center",
    "alerts.filter": "Filter",
    "alerts.all": "All",
    "alerts.critical": "Critical",
    "alerts.warning": "Warning",
    "alerts.warnings": "Warnings",
    "alerts.info": "Info",
    "alerts.unread": "Unread",
    "alerts.resolved": "Resolved",
    "alerts.view": "View",
    "alerts.noAlerts": "No alerts",
    "alerts.markRead": "Mark read",
    "alerts.criticalLabResult": "Critical Lab Result",
    "alerts.medicationStockCritical": "Medication Stock Critical",
    "alerts.missedCheckin": "Missed Medication Check-in",
    "alerts.lowStock": "Low Stock Warning",
    "alerts.scheduledAppointment": "Scheduled Appointment",
    "alerts.labNormal": "Lab Results Normal",
    // Medications
    "medications.inventory": "Medication Inventory",
    "medications.search": "Search medications...",
    "medications.totalMedications": "Total Medications",
    "medications.lowStock": "Low Stock",
    "medications.criticalStock": "Critical Stock",
    "medications.ordersPending": "Orders Pending",
    "medications.medication": "Medication",
    "medications.category": "Category",
    "medications.currentStock": "Current Stock",
    "medications.stockLevel": "Stock Level",
    "medications.monthlyUsage": "Monthly Usage",
    "medications.trend": "Trend",
    "medications.status": "Status",
    "medications.critical": "Critical",
    "medications.low": "Low",
    "medications.inStock": "In Stock",
    // Patients
    "patients.total": "Total Recipients",
    "patients.alive": "Alive",
    "patients.onDialysis": "On Dialysis",
    "patients.deceased": "Deceased",
    "patients.recipientsList": "Recipients List",
    "patients.export": "Export",
    "patients.newTransplant": "New Transplant",
    "patients.search": "Search patients...",
    "patients.organ": "Organ",
    "patients.allOrgans": "All Organs",
    "patients.allStatus": "All Status",
    "patients.name": "Name",
    "patients.ageGender": "Age/Gender",
    "patients.transplantDate": "Transplant Date",
    "patients.region": "Region",
    "patients.status": "Status",
    "patients.riskScore": "Risk Score",
  },
  ru: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Добавить пациента",
    "nav.logout": "Выход",
    "nav.dashboard": "Панель",
    "nav.patients": "Пациенты",
    "nav.medications": "Препараты",
    "nav.alerts": "Оповещения",
    "nav.reports": "Отчёты",
    "nav.analytics": "Аналитика",
    "dashboard.title": "Панель управления",
    "dashboard.subtitle": "Обзор пациентов с трансплантацией",
    "dashboard.totalPatients": "Всего пациентов",
    "dashboard.highRisk": "Высокий риск",
    "dashboard.mediumRisk": "Средний риск",
    "dashboard.activeAlerts": "Активные оповещения",
    "dashboard.riskDistribution": "Распределение рисков",
    "dashboard.noPatients": "Пациентов пока нет",
    "dashboard.highRiskPatients": "Пациенты высокого риска",
    "dashboard.noHighRisk": "Нет пациентов высокого риска",
    "dashboard.patient": "Пациент",
    "dashboard.organ": "Орган",
    "dashboard.daysPostTx": "Дней после Тх",
    "dashboard.keyLab": "Лаб. данные",
    "dashboard.risk": "Риск",
    "login.title": "TransplantCare",
    "login.subtitle": "Система управления пациентами с трансплантацией",
    "login.signIn": "Войти",
    "login.signUp": "Создать аккаунт",
    "login.signInDesc": "Введите данные для входа",
    "login.signUpDesc": "Введите данные для создания аккаунта",
    "login.fullName": "Полное имя",
    "login.email": "Электронная почта",
    "login.password": "Пароль",
    "login.createAccount": "Создать аккаунт",
    "login.alreadyHave": "Уже есть аккаунт?",
    "login.dontHave": "Нет аккаунта?",
    "login.accountCreated": "Аккаунт создан",
    "login.checkEmail": "Проверьте почту для подтверждения.",
    "login.forgotPassword": "Забыли пароль?",
    "login.resetPassword": "Сброс пароля",
    "login.resetDesc": "Введите email для получения ссылки сброса пароля",
    "login.sendResetLink": "Отправить ссылку",
    "login.resetSent": "Ссылка отправлена",
    "login.resetSentDesc": "Проверьте почту для ссылки сброса пароля.",
    "login.backToLogin": "Назад к входу",
    "login.newPassword": "Новый пароль",
    "login.confirmPassword": "Подтвердите пароль",
    "login.updatePassword": "Обновить пароль",
    "login.passwordUpdated": "Пароль обновлён",
    "login.passwordUpdatedDesc": "Теперь вы можете войти с новым паролем.",
    "login.passwordMismatch": "Пароли не совпадают",
    "role.welcome": "Добро пожаловать в TransplantCare",
    "role.selectRole": "Выберите роль для продолжения",
    "role.doctor": "Врач / Медицинский работник",
    "role.doctorDesc": "Управление пациентами, анализ рисков и контроль трансплантации",
    "role.patient": "Портал пациента",
    "role.patientDesc": "Просмотр состояния здоровья, результатов анализов и хронологии лечения",
    "role.support": "Поддержка",
    "role.supportDesc": "Помощь пользователям и управление запросами поддержки",
    "role.admin": "Администратор",
    "role.adminDesc": "Полное управление системой, пользователями и настройками",
    "add.selectOrgan": "Добавить пациента — Выбор органа",
    "add.chooseType": "Выберите тип трансплантации",
    "add.liverTransplant": "Трансплантация печени",
    "add.kidneyTransplant": "Трансплантация почки",
    "add.liverDesc": "Отслеживание ALT, AST, Такролимус, Билирубин",
    "add.kidneyDesc": "Отслеживание Креатинин, СКФ, История диализа",
    "add.patientInfo": "Информация о пациенте",
    "add.fullName": "Полное имя",
    "add.dob": "Дата рождения",
    "add.gender": "Пол",
    "add.male": "Мужской",
    "add.female": "Женский",
    "add.other": "Другой",
    "add.transplantDetails": "Детали трансплантации",
    "add.transplantNumber": "Номер трансплантации",
    "add.transplantDate": "Дата трансплантации",
    "add.rejectionType": "Тип отторжения",
    "add.dialysisHistory": "История диализа",
    "add.yes": "Да",
    "add.no": "Нет",
    "add.returnDialysisDate": "Дата возвращения на диализ",
    "add.biopsyResult": "Результат биопсии (необязательно)",
    "add.labResults": "Лабораторные результаты",
    "add.tacrolimus": "Уровень такролимуса",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Общий билирубин",
    "add.directBilirubin": "Прямой билирубин",
    "add.creatinine": "Креатинин",
    "add.egfr": "СКФ",
    "add.proteinuria": "Протеинурия",
    "add.potassium": "Калий",
    "add.save": "Сохранить пациента",
    "add.patientAdded": "Пациент добавлен",
    "add.addLiver": "Добавить пациента (Печень)",
    "add.addKidney": "Добавить пациента (Почка)",
    "detail.patientInfo": "Информация о пациенте",
    "detail.underReview": "На медицинском контроле",
    "detail.latestLabs": "Последние результаты анализов",
    "detail.aiAdvisory": "ИИ-консультация и проверка",
    "detail.approve": "Утвердить",
    "detail.orOverride": "или переопределить:",
    "detail.newRiskLevel": "Новый уровень риска",
    "detail.overrideReason": "Обязательная причина переопределения...",
    "detail.overrideRisk": "Переопределить риск",
    "detail.timeline": "Хронология",
    "detail.noEvents": "Нет событий",
    "detail.added": "Добавлен",
    "detail.dob": "Дата рождения",
    "detail.riskApproved": "Риск утверждён",
    "detail.provideReason": "Укажите уровень риска и причину",
    "detail.riskOverridden": "Риск переопределён",
    "detail.addLab": "Добавить анализ",
    "detail.addNewLab": "Добавить новые результаты анализов",
    "detail.saveLab": "Сохранить результаты",
    "detail.labAdded": "Результаты анализов добавлены",
    "detail.labAddedEvent": "Записаны новые результаты анализов",
    "detail.date": "Дата",
    "detail.labHistory": "История анализов",
    "home.healthStatus": "Ваше состояние здоровья",
    "home.name": "Имя",
    "home.organ": "Орган",
    "home.riskLevel": "Уровень риска",
    "home.highRiskWarning": "⚠️ На медицинском контроле. Ваша команда следит за вашим состоянием.",
    "home.careTimeline": "Хронология лечения",
    "home.noEvents": "Пока нет событий",
    "home.latestLabs": "Последние результаты анализов",
    "home.recorded": "Записано",
    "home.noLinked": "Запись пациента ещё не привязана к вашему аккаунту.",
    "home.loading": "Загрузка...",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.optional": "Необязательно",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.date": "Дата",
    "common.phone": "Телефон",
    "common.tests": "тестов",
    "upload.title": "Загрузить отчёт",
    "upload.uploadTitle": "Загрузка лабораторного отчёта",
    "upload.processing": "Обработка отчёта...",
    "upload.confirm": "Подтвердить результаты",
    "upload.description": "Загрузите фото или файл лабораторного отчёта. Если в файле есть результаты за несколько дат, каждая будет сохранена отдельно.",
    "upload.takePhoto": "Сделать фото",
    "upload.uploadFile": "Загрузить файл",
    "upload.aiProcessing": "AI извлекает лабораторные значения...",
    "upload.detectingDates": "Определяются даты, макет и названия тестов",
    "upload.datesDetected": "отдельных дат обнаружено — каждая будет сохранена как отдельный результат",
    "upload.dateLabel": "Дата:",
    "upload.enterDateManually": "Введите дату вручную",
    "upload.dateNotDetected": "Дата не определена",
    "upload.dateNotDetectedDesc": "Дата не определена — введите вручную:",
    "upload.valuesFound": "значений найдено",
    "upload.needsVerification": "требует проверки",
    "upload.lowConfidence": "Низкая уверенность — проверьте:",
    "upload.saveResults": "Сохранить результаты",
    "upload.confirmResults": "Подтвердить результаты",
    "upload.reupload": "Загрузить заново",
    "upload.resultsSaved": "Результаты сохранены для дат",
    "upload.verifyValues": "значений требуют проверки",
    "upload.lowConfidenceDesc": "Значения с низкой уверенностью выделены.",
    "upload.original": "Оригинал",
    "lab.noResults": "Нет результатов анализов",
    "lab.testName": "Название теста",
    "lab.value": "Значение",
    "lab.unit": "Единица",
    "lab.reference": "Норма",
    "lab.status": "Статус",
    "lab.normal": "Норма",
    "lab.high": "Высокий",
    "lab.borderline": "Пограничный",
    "lab.noTrendData": "Нет данных для трендов",
    "lab.latestLabs": "Последние анализы",
    "lab.labHistory": "История анализов",
    "lab.latest": "Последний",
    "risk.score": "Оценка риска",
    "risk.calculating": "Расчёт...",
    "risk.noLabData": "Результаты анализов не введены",
    "risk.factors": "Факторы риска:",
    "patientAlerts.title": "Оповещения",
    "patientAlerts.markAllRead": "Отметить все прочитанными",
    "edit.title": "Редактировать данные пациента",
    "edit.patientUpdated": "Данные пациента сохранены",
    "edit.enterName": "Введите имя",
    "edit.none": "Нет",
    "edit.acute": "Острый",
    "edit.chronic": "Хронический",
    "profile.overview": "Обзор",
    "profile.labResults": "Анализы",
    "profile.trends": "Тренды",
    "profile.risk": "Риск",
    "profile.timeline": "Хронология",
    "profile.patientInfo": "Информация о пациенте",
    "profile.fullName": "Полное имя",
    "profile.organType": "Тип органа",
    "profile.gender": "Пол",
    "profile.dob": "Дата рождения",
    "profile.transplantDate": "Дата трансплантации",
    "profile.transplant": "Трансплантация",
    "profile.highRiskWarning": "⚠️ Уровень риска повышен. Обратитесь к врачу как можно скорее.",
    "profile.careTimeline": "Хронология лечения",
    "profile.noEvents": "Нет записанных событий",
    "detail.patientNotFound": "Пациент не найден",
    "detail.confirmDelete": "Удалить пациента",
    "detail.confirmDeleteDesc": "Вы уверены, что хотите удалить этого пациента? Это действие нельзя отменить.",
    "detail.patientDeleted": "Пациент удалён",
    "detail.patientUpdated": "Данные пациента сохранены",
    "analytics.title": "Аналитика и статистика",
    "analytics.subtitle": "Национальная статистика трансплантации",
    "analytics.print": "Печать",
    "analytics.exportCSV": "Экспорт CSV",
    "analytics.filters": "Фильтры",
    "analytics.allYears": "Все годы",
    "analytics.allRegions": "Все регионы",
    "analytics.allOrgans": "Все органы",
    "analytics.reset": "Сброс",
    "analytics.transplantsByYear": "Трансплантации по годам",
    "analytics.survivalTrends": "Тренды выживаемости",
    "analytics.centerComparison": "Сравнение центров",
    "analytics.centerName": "Название центра",
    "analytics.region": "Регион",
    "analytics.total": "Всего",
    "analytics.kidney": "Почка",
    "analytics.liver": "Печень",
    "analytics.oneYearSurvival": "1 год выжив.",
    "analytics.threeYearSurvival": "3 года выжив.",
    "analytics.tashkent": "Ташкент",
    "analytics.samarkand": "Самарканд",
    "analytics.vakhidovCenter": "Республиканский центр им. Вахидова",
    "analytics.nephrologyCenter": "Центр нефрологии",
    "analytics.nationalMedicalCenter": "Национальный мед. центр",
    "analytics.childrenNationalCenter": "Детский нац. центр",
    "reports.title": "Отчёты и бюджет",
    "reports.medications": "Медикаменты",
    "reports.equipment": "Оборудование",
    "reports.personnel": "Персонал",
    "reports.facilities": "Помещения",
    "reports.totalBudget": "Общий бюджет",
    "reports.spentYTD": "Потрачено",
    "reports.remaining": "Остаток",
    "reports.patientsCovered": "Пациенты",
    "reports.annualAllocation": "Годовой бюджет",
    "reports.patientTrends": "Тренды пациентов",
    "reports.patients": "Пациенты",
    "reports.transplants": "Трансплантации",
    "reports.budgetAllocation": "Распределение бюджета",
    "reports.departmentUtilization": "Использование по отделам",
    "reports.availableReports": "Доступные отчёты",
    "reports.generateNew": "Новый отчёт",
    "reports.monthlyPatientRegistry": "Месячный реестр пациентов",
    "reports.quarterlyTransplantStats": "Квартальная статистика",
    "reports.medicationUsageReport": "Отчёт по медикаментам",
    "reports.regionalDistribution": "Региональный анализ",
    "alerts.alertCenter": "Центр оповещений",
    "alerts.filter": "Фильтр",
    "alerts.all": "Все",
    "alerts.critical": "Критические",
    "alerts.warning": "Предупреждения",
    "alerts.warnings": "Предупреждения",
    "alerts.info": "Информация",
    "alerts.unread": "Непрочитанные",
    "alerts.resolved": "Решённые",
    "alerts.view": "Просмотр",
    "alerts.criticalLabResult": "Критический анализ",
    "alerts.medicationStockCritical": "Критический запас лекарств",
    "alerts.missedCheckin": "Пропущен приём",
    "alerts.lowStock": "Низкий запас",
    "alerts.scheduledAppointment": "Запланированный приём",
    "alerts.labNormal": "Анализы в норме",
    "medications.inventory": "Склад медикаментов",
    "medications.search": "Поиск...",
    "medications.totalMedications": "Всего препаратов",
    "medications.lowStock": "Низкий запас",
    "medications.criticalStock": "Критический запас",
    "medications.ordersPending": "Ожидают заказа",
    "medications.medication": "Препарат",
    "medications.category": "Категория",
    "medications.currentStock": "Текущий запас",
    "medications.stockLevel": "Уровень запаса",
    "medications.monthlyUsage": "Месячный расход",
    "medications.trend": "Тренд",
    "medications.status": "Статус",
    "medications.critical": "Критический",
    "medications.low": "Низкий",
    "medications.inStock": "В наличии",
    "patients.total": "Всего реципиентов",
    "patients.alive": "Живы",
    "patients.onDialysis": "На диализе",
    "patients.deceased": "Умершие",
    "patients.recipientsList": "Список реципиентов",
    "patients.export": "Экспорт",
    "patients.newTransplant": "Новая трансплантация",
    "patients.search": "Поиск пациентов...",
    "patients.organ": "Орган",
    "patients.allOrgans": "Все органы",
    "patients.allStatus": "Все статусы",
    "patients.name": "Имя",
    "patients.ageGender": "Возраст/Пол",
    "patients.transplantDate": "Дата трансплантации",
    "patients.region": "Регион",
    "patients.status": "Статус",
    "patients.riskScore": "Риск",
  },
  uz: {
    "app.name": "TransplantCare",
    "nav.addPatient": "Bemor qo'shish",
    "nav.logout": "Chiqish",
    "nav.dashboard": "Boshqaruv",
    "nav.patients": "Bemorlar",
    "nav.medications": "Dorilar",
    "nav.alerts": "Ogohlantirishlar",
    "nav.reports": "Hisobotlar",
    "nav.analytics": "Analitika",
    "dashboard.title": "Boshqaruv paneli",
    "dashboard.subtitle": "Transplantatsiya bemorlarining umumiy ko'rinishi",
    "dashboard.totalPatients": "Jami bemorlar",
    "dashboard.highRisk": "Yuqori xavf",
    "dashboard.mediumRisk": "O'rta xavf",
    "dashboard.activeAlerts": "Faol ogohlantirishlar",
    "dashboard.riskDistribution": "Xavf taqsimoti",
    "dashboard.noPatients": "Hali bemorlar yo'q",
    "dashboard.highRiskPatients": "Yuqori xavfli bemorlar",
    "dashboard.noHighRisk": "Yuqori xavfli bemorlar yo'q",
    "dashboard.patient": "Bemor",
    "dashboard.organ": "Organ",
    "dashboard.daysPostTx": "Tx dan keyin kun",
    "dashboard.keyLab": "Lab. ma'lumot",
    "dashboard.risk": "Xavf",
    "login.title": "TransplantCare",
    "login.subtitle": "Transplantatsiya bemorlarini boshqarish tizimi",
    "login.signIn": "Kirish",
    "login.signUp": "Ro'yxatdan o'tish",
    "login.signInDesc": "Davom etish uchun ma'lumotlaringizni kiriting",
    "login.signUpDesc": "Hisob yaratish uchun ma'lumotlaringizni kiriting",
    "login.fullName": "To'liq ism",
    "login.email": "Elektron pochta",
    "login.password": "Parol",
    "login.createAccount": "Hisob yaratish",
    "login.alreadyHave": "Hisobingiz bormi?",
    "login.dontHave": "Hisobingiz yo'qmi?",
    "login.accountCreated": "Hisob yaratildi",
    "login.checkEmail": "Hisobingizni tasdiqlash uchun pochtangizni tekshiring.",
    "login.forgotPassword": "Parolni unutdingizmi?",
    "login.resetPassword": "Parolni tiklash",
    "login.resetDesc": "Parolni tiklash havolasini olish uchun emailingizni kiriting",
    "login.sendResetLink": "Havola yuborish",
    "login.resetSent": "Havola yuborildi",
    "login.resetSentDesc": "Parolni tiklash havolasi uchun pochtangizni tekshiring.",
    "login.backToLogin": "Kirishga qaytish",
    "login.newPassword": "Yangi parol",
    "login.confirmPassword": "Parolni tasdiqlang",
    "login.updatePassword": "Parolni yangilash",
    "login.passwordUpdated": "Parol yangilandi",
    "login.passwordUpdatedDesc": "Endi yangi parolingiz bilan kirishingiz mumkin.",
    "login.passwordMismatch": "Parollar mos kelmaydi",
    "role.welcome": "TransplantCare ga xush kelibsiz",
    "role.selectRole": "Davom etish uchun rolingizni tanlang",
    "role.doctor": "Shifokor / Tibbiy xodim",
    "role.doctorDesc": "Bemorlarni boshqarish, xavflarni tahlil qilish",
    "role.patient": "Bemor portali",
    "role.patientDesc": "Sog'lik holatingiz va tahlil natijalarini ko'ring",
    "role.support": "Qo'llab-quvvatlash",
    "role.supportDesc": "Foydalanuvchilarga yordam berish",
    "role.admin": "Administrator",
    "role.adminDesc": "Tizimni to'liq boshqarish",
    "add.selectOrgan": "Bemor qo'shish — Organ tanlash",
    "add.chooseType": "Transplantatsiya turini tanlang",
    "add.liverTransplant": "Jigar transplantatsiyasi",
    "add.kidneyTransplant": "Buyrak transplantatsiyasi",
    "add.liverDesc": "ALT, AST, Takrolimus, Bilirubin kuzatuvi",
    "add.kidneyDesc": "Kreatinin, SKF, Dializ tarixi kuzatuvi",
    "add.patientInfo": "Bemor ma'lumotlari",
    "add.fullName": "To'liq ism",
    "add.dob": "Tug'ilgan sana",
    "add.gender": "Jinsi",
    "add.male": "Erkak",
    "add.female": "Ayol",
    "add.other": "Boshqa",
    "add.transplantDetails": "Transplantatsiya tafsilotlari",
    "add.transplantNumber": "Transplantatsiya raqami",
    "add.transplantDate": "Transplantatsiya sanasi",
    "add.rejectionType": "Rad etish turi",
    "add.dialysisHistory": "Dializ tarixi",
    "add.yes": "Ha",
    "add.no": "Yo'q",
    "add.returnDialysisDate": "Dializ ga qaytish sanasi",
    "add.biopsyResult": "Biopsiya natijasi (ixtiyoriy)",
    "add.labResults": "Laboratoriya natijalari",
    "add.tacrolimus": "Takrolimus darajasi",
    "add.alt": "ALT",
    "add.ast": "AST",
    "add.totalBilirubin": "Umumiy bilirubin",
    "add.directBilirubin": "To'g'ridan-to'g'ri bilirubin",
    "add.creatinine": "Kreatinin",
    "add.egfr": "SKF",
    "add.proteinuria": "Proteinuriya",
    "add.potassium": "Kaliy",
    "add.save": "Bemorni saqlash",
    "add.patientAdded": "Bemor qo'shildi",
    "add.addLiver": "Jigar bemori qo'shish",
    "add.addKidney": "Buyrak bemori qo'shish",
    "detail.patientInfo": "Bemor ma'lumotlari",
    "detail.underReview": "Tibbiy nazorat ostida",
    "detail.latestLabs": "So'nggi tahlil natijalari",
    "detail.aiAdvisory": "AI maslahat va tekshiruv",
    "detail.approve": "Tasdiqlash",
    "detail.orOverride": "yoki o'zgartirish:",
    "detail.newRiskLevel": "Yangi xavf darajasi",
    "detail.overrideReason": "O'zgartirish uchun majburiy sabab...",
    "detail.overrideRisk": "Xavfni o'zgartirish",
    "detail.timeline": "Vaqt jadvali",
    "detail.noEvents": "Hodisalar yo'q",
    "detail.added": "Qo'shilgan",
    "detail.dob": "Tug'ilgan sana",
    "detail.riskApproved": "Xavf tasdiqlandi",
    "detail.provideReason": "Xavf darajasi va sababini kiriting",
    "detail.riskOverridden": "Xavf o'zgartirildi",
    "detail.addLab": "Tahlil qo'shish",
    "detail.addNewLab": "Yangi tahlil natijalari qo'shish",
    "detail.saveLab": "Natijalarni saqlash",
    "detail.labAdded": "Tahlil natijalari qo'shildi",
    "detail.labAddedEvent": "Yangi tahlil natijalari qayd etildi",
    "detail.date": "Sana",
    "detail.labHistory": "Tahlillar tarixi",
    "home.healthStatus": "Sog'lik holatingiz",
    "home.name": "Ism",
    "home.organ": "Organ",
    "home.riskLevel": "Xavf darajasi",
    "home.highRiskWarning": "⚠️ Tibbiy nazorat ostida.",
    "home.careTimeline": "Davolash vaqt jadvali",
    "home.noEvents": "Hali hodisalar yo'q",
    "home.latestLabs": "So'nggi tahlil natijalari",
    "home.recorded": "Qayd etilgan",
    "home.noLinked": "Hisobingizga bemor yozuvi hali bog'lanmagan.",
    "home.loading": "Yuklanmoqda...",
    "common.loading": "Yuklanmoqda...",
    "common.error": "Xatolik",
    "common.optional": "Ixtiyoriy",
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.delete": "O'chirish",
    "common.edit": "Tahrirlash",
    "common.date": "Sana",
    "common.phone": "Telefon",
    "common.tests": "ta test",
    "upload.title": "Tahlil yuklash",
    "upload.uploadTitle": "Laboratoriya hisobotini yuklash",
    "upload.processing": "Hisobot qayta ishlanmoqda...",
    "upload.confirm": "Natijalarni tasdiqlang",
    "upload.description": "Lab hisobotingizning rasmi yoki faylini yuklang. Bir faylda bir nechta sanadagi natijalar bo'lsa, har biri alohida saqlanadi.",
    "upload.takePhoto": "Rasm olish",
    "upload.uploadFile": "Fayl yuklash",
    "upload.aiProcessing": "AI yordamida lab qiymatlari ajratilmoqda...",
    "upload.detectingDates": "Sanalar, maket va test nomlari aniqlanmoqda",
    "upload.datesDetected": "ta alohida sana aniqlandi — har biri alohida lab natijasi sifatida saqlanadi",
    "upload.dateLabel": "Sana:",
    "upload.enterDateManually": "Sanani qo'lda kiriting",
    "upload.dateNotDetected": "Sana aniqlanmadi",
    "upload.dateNotDetectedDesc": "Sana aniqlanmadi — qo'lda kiriting:",
    "upload.valuesFound": "ta qiymat topildi",
    "upload.needsVerification": "ta tekshirish kerak",
    "upload.lowConfidence": "Past ishonchlilik — tekshiring:",
    "upload.saveResults": "Natijalarni saqlash",
    "upload.confirmResults": "Natijalarni tasdiqlash",
    "upload.reupload": "Qayta yuklash",
    "upload.resultsSaved": "Natijalar saqlandi",
    "upload.verifyValues": "ta qiymat tekshirishni talab qiladi",
    "upload.lowConfidenceDesc": "Past ishonchlilikdagi qiymatlar ajratib ko'rsatilgan.",
    "upload.original": "Asl nusxa",
    "lab.noResults": "Tahlil natijalari mavjud emas",
    "lab.testName": "Test nomi",
    "lab.value": "Qiymat",
    "lab.unit": "Birlik",
    "lab.reference": "Norma",
    "lab.status": "Holat",
    "lab.normal": "Normal",
    "lab.high": "Yuqori",
    "lab.borderline": "Chegaraviy",
    "lab.noTrendData": "Trend ma'lumotlari mavjud emas",
    "lab.latestLabs": "Oxirgi tahlillar",
    "lab.labHistory": "Tahlillar tarixi",
    "lab.latest": "Oxirgi",
    "risk.score": "Xavf bahosi",
    "risk.calculating": "Hisoblanmoqda...",
    "risk.noLabData": "Tahlil natijalari kiritilmagan",
    "risk.factors": "Xavf omillari:",
    "patientAlerts.title": "Ogohlantirishlar",
    "patientAlerts.markAllRead": "Barchasini o'qildi",
    "edit.title": "Bemor ma'lumotlarini tahrirlash",
    "edit.patientUpdated": "Bemor ma'lumotlari saqlandi",
    "edit.enterName": "Ismni kiriting",
    "edit.none": "Yo'q",
    "edit.acute": "O'tkir",
    "edit.chronic": "Surunkali",
    "profile.overview": "Umumiy",
    "profile.labResults": "Tahlillar",
    "profile.trends": "Trendlar",
    "profile.risk": "Xavf",
    "profile.timeline": "Vaqt jadvali",
    "profile.patientInfo": "Bemor ma'lumotlari",
    "profile.fullName": "To'liq ism",
    "profile.organType": "Organ turi",
    "profile.gender": "Jinsi",
    "profile.dob": "Tug'ilgan sana",
    "profile.transplantDate": "Transplantatsiya sanasi",
    "profile.transplant": "Transplantatsiya",
    "profile.highRiskWarning": "⚠️ Xavf darajangiz yuqori. Imkon qadar tezroq shifokoringizga murojaat qiling.",
    "profile.careTimeline": "Davolash vaqt jadvali",
    "profile.noEvents": "Hodisalar qayd etilmagan",
    "detail.patientNotFound": "Bemor topilmadi",
    "detail.confirmDelete": "Bemorni o'chirish",
    "detail.confirmDeleteDesc": "Haqiqatan ham bu bemorni o'chirmoqchimisiz? Bu amalni qaytarib bo'lmaydi.",
    "detail.patientDeleted": "Bemor o'chirildi",
    "detail.patientUpdated": "Bemor ma'lumotlari saqlandi",
    "analytics.title": "Analitika va statistika",
    "analytics.subtitle": "Milliy transplantatsiya statistikasi",
    "analytics.print": "Chop etish",
    "analytics.exportCSV": "CSV eksport",
    "analytics.filters": "Filtrlar",
    "analytics.allYears": "Barcha yillar",
    "analytics.allRegions": "Barcha hududlar",
    "analytics.allOrgans": "Barcha organlar",
    "analytics.reset": "Tozalash",
    "analytics.transplantsByYear": "Yillar bo'yicha transplantatsiyalar",
    "analytics.survivalTrends": "Yashash trendlari",
    "analytics.centerComparison": "Markazlar taqqoslash",
    "analytics.centerName": "Markaz nomi",
    "analytics.region": "Hudud",
    "analytics.total": "Jami",
    "analytics.kidney": "Buyrak",
    "analytics.liver": "Jigar",
    "analytics.oneYearSurvival": "1 yillik",
    "analytics.threeYearSurvival": "3 yillik",
    "analytics.tashkent": "Toshkent",
    "analytics.samarkand": "Samarqand",
    "analytics.vakhidovCenter": "Vohidov nomidagi Respublika markazi",
    "analytics.nephrologyCenter": "Nefrologiya markazi",
    "analytics.nationalMedicalCenter": "Milliy tibbiyot markazi",
    "analytics.childrenNationalCenter": "Bolalar milliy markazi",
    "reports.title": "Hisobotlar va byudjet",
    "reports.medications": "Dorilar",
    "reports.equipment": "Uskunalar",
    "reports.personnel": "Xodimlar",
    "reports.facilities": "Binolar",
    "reports.totalBudget": "Umumiy byudjet",
    "reports.spentYTD": "Sarflangan",
    "reports.remaining": "Qoldiq",
    "reports.patientsCovered": "Bemorlar",
    "reports.annualAllocation": "Yillik byudjet",
    "reports.patientTrends": "Bemor trendlari",
    "reports.patients": "Bemorlar",
    "reports.transplants": "Transplantatsiyalar",
    "reports.budgetAllocation": "Byudjet taqsimoti",
    "reports.departmentUtilization": "Bo'limlar bo'yicha foydalanish",
    "reports.availableReports": "Mavjud hisobotlar",
    "reports.generateNew": "Yangi hisobot",
    "reports.monthlyPatientRegistry": "Oylik bemor reestri",
    "reports.quarterlyTransplantStats": "Choraklik statistika",
    "reports.medicationUsageReport": "Dori foydalanish hisoboti",
    "reports.regionalDistribution": "Hududiy tahlil",
    "alerts.alertCenter": "Ogohlantirish markazi",
    "alerts.filter": "Filtr",
    "alerts.all": "Barchasi",
    "alerts.critical": "Kritik",
    "alerts.warning": "Ogohlantirish",
    "alerts.warnings": "Ogohlantirishlar",
    "alerts.info": "Ma'lumot",
    "alerts.unread": "O'qilmagan",
    "alerts.resolved": "Hal qilingan",
    "alerts.view": "Ko'rish",
    "alerts.criticalLabResult": "Kritik tahlil natijasi",
    "alerts.medicationStockCritical": "Dori zahirasi kritik",
    "alerts.missedCheckin": "Dori qabuli o'tkazib yuborildi",
    "alerts.lowStock": "Kam zahira",
    "alerts.scheduledAppointment": "Rejalashtirilgan qabul",
    "alerts.labNormal": "Tahlillar norma",
    "medications.inventory": "Dori ombori",
    "medications.search": "Qidiruv...",
    "medications.totalMedications": "Jami dorilar",
    "medications.lowStock": "Kam zahira",
    "medications.criticalStock": "Kritik zahira",
    "medications.ordersPending": "Kutilayotgan buyurtmalar",
    "medications.medication": "Dori",
    "medications.category": "Kategoriya",
    "medications.currentStock": "Joriy zahira",
    "medications.stockLevel": "Zahira darajasi",
    "medications.monthlyUsage": "Oylik sarflanish",
    "medications.trend": "Trend",
    "medications.status": "Holat",
    "medications.critical": "Kritik",
    "medications.low": "Kam",
    "medications.inStock": "Mavjud",
    "patients.total": "Jami retsipiyentlar",
    "patients.alive": "Tirik",
    "patients.onDialysis": "Dializ da",
    "patients.deceased": "Vafot etgan",
    "patients.recipientsList": "Retsipiyentlar ro'yxati",
    "patients.export": "Eksport",
    "patients.newTransplant": "Yangi transplantatsiya",
    "patients.search": "Bemorlarni qidirish...",
    "patients.organ": "Organ",
    "patients.allOrgans": "Barcha organlar",
    "patients.allStatus": "Barcha holatlar",
    "patients.name": "Ism",
    "patients.ageGender": "Yosh/Jinsi",
    "patients.transplantDate": "Transplantatsiya sanasi",
    "patients.region": "Hudud",
    "patients.status": "Holat",
    "patients.riskScore": "Xavf bali",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-lang");
    return (saved as Language) || "en";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("app-lang", newLang);
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
